### ISSUE TITLE
Create Translation project on Transifex.com

### ISSUE THREAD

**Issue by luzfcb** [django-guardian/django-guardian#145]
Hi, I want to translate Django-guardian to Portuguese of Brazil. You could create the project of translating the Django-guardian on Transifex and put myself as maintainer of the version in Portuguese of Brazil.My username is: maz

**Comment by brianmay** [comment]
Is Transifex still desirable?

I note that the blog post referenced above on using it with Django is gone.

**Comment by brianmay** [comment]
Transifex is not a free product:

https://www.transifex.com/pricing/

I have no idea why it might be a good idea, however even if it was we have not budget for django-guardian development.

Closing.

**Comment by ad-m** [comment]
I have an Open Source project. Where do I sign up?

We love Open Source! Open source projects can sign up for free using the
option above and enjoy unlimited translations.

Wysłano z urządzenia mobilnego.
17 gru 2015 08:12 "Brian May" <notifications@github.com> napisał(a):

**Comment by brianmay** [comment]
@ad-m Are you some how connected with transifex?

I have no idea what it is, what it provides, or why it might actually by useful for Guardian.

The fact the referenced blog post for using it with Django has vanished does not help.
