### ISSUE TITLE
In admin.. how to view the obj and not the full list

### ISSUE THREAD

**Issue by po5i** [django-guardian/django-guardian#157]
Maybe is a n00b question but still.. 

I installed the app and set some object-level permissions (change object) for one object (for testing purposes) to one user. 

This user is a staff member, so he can enter the admin area and see this message "You don't have permission to edit anything."

How can this user edit the object he has permission on if he cannot enter the list view in the  module? Is any way to implement this? Where should I begin?

Just for the record, if I give the permission to "change" in the user edit view (in admin) He can change every object, and that's not funny..

**Comment by brianmay** [comment]
This is a limitation in Django admin that we can't really fix in Guardian. So closing this report.

Having said that, see #305.
