### ISSUE TITLE
REUSE_DB for tests fails when ANONYMOUS_USER_ID as -1

### ISSUE THREAD

**Issue by fmarani** [django-guardian/django-guardian#158]
I am crossposting an issue from django-nose, I believe it belongs more to django-guardian

Briefly, when setting the default ANONYMOUS_USER_ID set to -1, tests work perfectly the first time round. However, when using REUSE_DB, on a second pass, django_nose cannot reset the database successfully.

The error given is as follows:

django.db.utils.DatabaseError: setval: value -1 is out of bounds for sequence "auth_user_id_seq" (1..9223372036854775807)

Using: Django 1.4.3, django-guardian 1.1.1, postgres 9.1 with postgis 1.5.
Django engine: django.contrib.gis.db.backends.postgis

**Comment by Mactory** [comment]
The error still exists for me today. Any solution yet?

**Comment by tartley** [comment]
Ditto.

**Comment by Mactory** [comment]
Look here for the workaround I found: https://github.com/django-nose/django-nose/issues/119#issuecomment-111466768

**Comment by brianmay** [comment]
Postgresql doesn't like having -1 as the primary key value? Is that the issue here?

**Comment by tartley** [comment]
Sounds likely. Follow Mactory's link to see a solution that worked for me, including using '99999' instead of '-1'

**Comment by brianmay** [comment]
Was almost going to close this.

However thinking about it some more, I don't like the fact `ANONYMOUS_USER_ID` needs to be specified. Different databases have different ways of allocating userid's and I don't think we should be trying to do that ourselves. For example, when the id does reach 99999, I think there could be problems when trying to create an object with that id and Django finds it was already taken.

I see a better approach is to rename `ANONYMOUS_DEFAULT_USERNAME_VALUE` to `ANONYMOUS_USERNAME` and then lookup the id based on this.

@lukaszb Is there any reason this was implemented the way it was?
