### ISSUE TITLE
get_users_with_perms raises django FieldError Cannot resolve keyword u'userobjectpermission' into field

### ISSUE THREAD

**Issue by OdifYltsaeb** [django-guardian/django-guardian#182]
this is one werid issue.

I have a form:

class PartnerForm(forms.ModelForm):
	class Meta:
		model = Partner
		fields = ['name', 'referencenumber', 'clients', 'admins', 'default_base_name']

	def __init__(self, *args, **kwargs):
		super(PartnerForm, self).__init__(*args, **kwargs)
		if not self.instance:
			raise Exception(u"Missing form instance")
		others = Partner.objects.exclude(id = self.instance.id)
		d = {'other partners' : ','.join([str(other.id) for other in others])}
		sql  = 'SELECT * FROM account_account aa WHERE aa.id NOT IN (SELECT account_id FROM account_partner_clients '
		sql += 'WHERE partner_id in (%(other partners)s)) ORDER BY name'
		self.fields['clients'].query_set = Account.objects.raw(sql)

		a = Account.objects.get(referencenumber = self.instance.referencenumber)

		self.fields['admins'].query_set = get_users_with_perms(a)

When i initialize the form i get fielderrror. Example in django shell:
>>> from account.forms import PartnerForm
>>> from account.models import Partner
>>> p = Partner.objects.get(id = 3)
>>> f = PartnerForm(instance = p)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/alan/projects/resellertools/account/forms.py", line 108, in __init__
    self.fields['admins'].query_set = get_users_with_perms(a)
  File "/home/alan/python/django-guardian-1.1.1/guardian/shortcuts.py", line 225, in get_users_with_perms
    return get_user_model().objects.filter(qset).distinct()
  File "/home/alan/python/Django-1.4.2/django/db/models/manager.py", line 143, in filter
    return self.get_query_set().filter(*args, **kwargs)
  File "/home/alan/python/Django-1.4.2/django/db/models/query.py", line 624, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/alan/python/Django-1.4.2/django/db/models/query.py", line 642, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/alan/python/Django-1.4.2/django/db/models/sql/query.py", line 1247, in add_q
    self.add_q(child, used_aliases, force_having=force_having)
  File "/home/alan/python/Django-1.4.2/django/db/models/sql/query.py", line 1247, in add_q
    self.add_q(child, used_aliases, force_having=force_having)
  File "/home/alan/python/Django-1.4.2/django/db/models/sql/query.py", line 1250, in add_q
    can_reuse=used_aliases, force_having=force_having)
  File "/home/alan/python/Django-1.4.2/django/db/models/sql/query.py", line 1122, in add_filter
    process_extras=process_extras)
  File "/home/alan/python/Django-1.4.2/django/db/models/sql/query.py", line 1316, in setup_joins
    "Choices are: %s" % (name, ", ".join(names)))
FieldError: Cannot resolve keyword u'userobjectpermission' into field. Choices are: date_joined, defaultsettings, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, partner, password, user_permissions, username, useropenid

BUT!
When i test it in shell like this:
>>> from account.models import Account
>>> from guardian.shortcuts import get_users_with_perms
>>> a = Account.objects.get(id = 202)
>>> u = get_users_with_perms(a)
>>> u
[]
>>> from account.forms import PartnerForm
>>> from account.models import Partner
>>> p = Partner.objects.get(id = 3)
>>> f = PartnerForm(instance = p)
>>> f
<account.forms.PartnerForm object at 0x2fe9ed0>

No error is raised. What i'm trying to point out is that if you do things in different order, you get different results. Which is not how things should work imo. forgot to say that i use guardian 1.1.1 downloaded from pypi and django 1.4.2.

**Comment by brianmay** [comment]
Was this using Direct Foreign Keys by any chance?

Not enough information to tell. Possibly the same as #206???

**Comment by brianmay** [comment]
This bug is rather old, and very possible already fixed. Closing.

If I am wrong, please say so and I will reopen.
