### ISSUE TITLE
Using get_objects_for_user when perms is unicode string fails on 1.2.0

### ISSUE THREAD

**Issue by ircubic** [django-guardian/django-guardian#201]
I encountered this problem when using django-rest-framework's `DjangoObjectPermissionFilter` with django-guardian. After some digging (I think) I tracked the problem down to `DjangoObjectPermissionFilter` constructing a unicode string for `perms`. This causes the following check in `get_objects_for_user` to fail:

    if isinstance(perms, str):
        perms = [perms]

This then causes `get_objects_for_user` to continue processing `perms` (the unicode string) as if it was a collection, which obviously is not correct. Confusingly, this code does not seem to be present in github (it checks against `basestring`, which I believe should work), otherwise I'd submit a pull request.

Reverting to 1.1.1 fixes the problem.

**Comment by brianmay** [comment]
I believe this has been fixed in 49fd61c9fbf0b8ae35ab111b515d8a82a3343ca0:

```diff
-    if isinstance(cls, str):
+    if isinstance(cls, basestring):
```
