### ISSUE TITLE
Direct foreign keys : keyword error

### ISSUE THREAD

**Issue by nephthys** [django-guardian/django-guardian#206]
Hi,

I use the "Direct foreign keys" function and I get the following error :
```
/admin/hotels/hotel/1/permissions/
Cannot resolve keyword 'hoteluserobjectpermission' into field. Choices are: date_joined, email, [...], password, user_permissions, username, userobjectpermission_
```

My models (which work without direct foreign keys) : 

```python
class Hotel(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField(unique=True, max_length=150)

class HotelUserObjectPermission(UserObjectPermissionBase):
    content_object = models.ForeignKey(Hotel)

class HotelGroupObjectPermission(GroupObjectPermissionBase):
    content_object = models.ForeignKey(Hotel)
```

I must have missed something or misunderstood? 

Thanks for your help.

**Comment by brianmay** [comment]
Think we are going to need a stack trace to help resolve this. However I note the issue was created in April 2014, so suspect this is unlikely...

**Comment by brianmay** [comment]
This bug is rather old, and very possible already fixed. Closing.

If I am wrong, please say so and I will reopen.
