### ISSUE TITLE
`GuardedModelAdminMixin.queryset` method should be renamed `get_queryset`

### ISSUE THREAD

**Issue by denilsonsa** [django-guardian/django-guardian#207]
How to reproduce:

1. Create a virtualenv like this:
    * Python 3.3
    * Django 1.6.3
    * django-guardian 1.2.0
    * mysql-connector-python 1.1.6 ([instructions about installing/configuring mysql-connector-python](http://bunwich.blogspot.ca/2014/02/finally-mysql-connector-that-works-with.html))

2. Create a simple project using Guardian.
3. `./manage.py runserver`
4. Open http://127.0.0.1:8000/admin/

What happens:

> PendingDeprecationWarning at /admin/
> `GuardedModelAdminMixin.queryset` method should be renamed `get_queryset`.

It is worth noting that using PyMySQL 0.6.2 ([as these instructions](http://stackoverflow.com/a/21416007/)) does not trigger this deprecation warning.

**Comment by brianmay** [comment]
I believe this was fixed in 1.2.5.
