### ISSUE TITLE
Adding object to request in decorators

### ISSUE THREAD

**Issue by mativs** [django-guardian/django-guardian#215]
I'm not sure if it's a very elegant solution, so I first wan't to know your opinion.

On permission_required decorator a property can be set to the request object with the recent lookup to the database. In that situation the user won't need to hit the database again, just look for the property on the request. 

What do you think? I can make a fork and try to add the feature.

**Comment by brianmay** [comment]
Not sure I understand the problem trying to be solved here. If it is just removing one extra lookup on the database, I suspect there are more important optimizations we should be doing first. As such, closing for now.
