### ISSUE TITLE
Minor Import inconvience

### ISSUE THREAD

**Issue by abraithwaite** [django-guardian/django-guardian#222]
I noticed that guardian doesn't import all it's submodules in the top level package `__init__.py`.

While this is normal python behavior, it's convenient to be able to do:

```python
from compat import guardian
guardian.shortcuts.get_objects_for_user(...)
```

If you want I can make a pull request with a simple patch, but I didn't see a style guide and I noticed you were using relative imports which I'm unfamiliar with so I decided to make an issue instead.

**Comment by brianmay** [comment]
It would appear that this issue has been fixed in the djangorestframework, so closing.

If you think this is an issue that should be fixed in Guardian, please provide some examples of packages that already do this. I had a quick look, and couldn't find anything.
