### ISSUE TITLE
guardian_groupobjectpermission table is confuse for me

### ISSUE THREAD

**Issue by xiaods** [django-guardian/django-guardian#226]
I use default settings. when i run  assign_perm("one.view_fields", group). it works well. but I found the data is store to auth_group_permissions, not guardian_groupobjectpermission. So i am not sure what action can store to guardian_groupobjectpermission table.
I search the docs and source code, i am not found any clues? so  anyone can give me a hint.

**Comment by brianmay** [comment]
Seems like the requester may have used the global `assign_perm` function by mistake, not the per object `assign_perm` function. Closing.
