### ISSUE TITLE
Subclassing django.contrib.auth.Group

### ISSUE THREAD

**Issue by devangmundhra** [django-guardian/django-guardian#229]
Will the group based permission work if the group is based on a subclass of `django.contrib.auth.Group`? It seems like django-guardian uses `isinstance(object) == Group` to check if the object to be permitted is `User` or `Group`, so it should work.

I want to add some additional information to the `Group`, thats why I am trying to use a `DerivedGroup`.

**Comment by arpheno** [comment]
How did this work out for you? I'm having a hard time doing this.

**Comment by devangmundhra** [comment]
Unfortunately it didn't work out so well. I created my own permission model using m2m models and through classes

**Comment by arpheno** [comment]
For future reference I'd like to point out that I managed to do this, if not cleanly that at least something I can work with.
You can subclass auth.Group and just create those objects and leave the M2M alone, or even attach a through model to it. ( from user to auth.group). Everything works beautifully so far. If more people run into this i will make a blog post about it. 
Please have a look at commit https://github.com/arpheno/eestecnet/commit/6e78252fee04adbb32d59444f1e7bb5fd1ffdf95#diff-ea1fd0db0c4d0b17e7d1b3ac49ae0cbd

**Comment by brianmay** [comment]
There don't appear to be any specific issues that can be fixed with Guardian here, so closing this issue.
