### ISSUE TITLE
Migrating to using Direct foreign keys

### ISSUE THREAD

**Issue by cancan101** [django-guardian/django-guardian#231]
If I currently do not use "Direct foreign keys" for object permissioning, but I want to start using them, what do I need to do to migrate data from the existing general `UserObjectPermission` and `GroupObjectPermission` models to the new model specific models?

I recommend adding a section to the docs addressing this issue.

**Comment by brianmay** [comment]
I think how you do this is very much dependent on your application, and we cannot really help in guardian. However if somebody does solve this problem with the Django 1.7+ migration system, feel free to contribute your solution.

For now closing.
