### ISSUE TITLE
Show note when editing inactive user's permissions at admin

### ISSUE THREAD

**Issue by lukaszb** [django-guardian/django-guardian#237]
Currently we save object permissions for inactive users but once response is back, admin can see no permissions enabled for the user. This is because that view checks for permissions, it doesn't simply read database.

We need at least inform admin that she is editing permissions for **inactive** users and won't see any permissions enabled until the user is activated.

**Comment by brianmay** [comment]
@mitar do you think this is this fixed by #403?

**Comment by brianmay** [comment]
Have conducted tests using example_project, and permissions still show up even when user is marked as inactive. As a result, I am going to close this. If I was wrong, please tell me and I will reopen.

**Comment by mitar** [comment]
Hm, I do not really see where inactive status is checked at all. So I do not see how inactive flag would hide permissions previously.

**Comment by brianmay** [comment]
Weird. In any case, I didn't see any problems. We can reopen if required.

**Comment by mitar** [comment]
No, I just do not understand the initial ticket, this is it.

**Comment by mitar** [comment]
Ah, my mistake, there is a check for `is_active` in `get_perms`, which is not there in `get_user_perms` and `get_group_perms`.
