### ISSUE TITLE
I am doing the right thing of Implementing bulk_assign_perm function?

### ISSUE THREAD

**Issue by vitan** [django-guardian/django-guardian#242]
Hi,

I override django-guardian to support such bulk_assign_perm(perm, users_or_groups, objs=None) function in my project, and I'd like to clean them feedback to upstream.

can u tell me if I am doing the right thing before I start to do?

here is the unfinished commit https://github.com/vitan/django-guardian/commit/659bebf34d0bac18db485c05d21a35aa78c0d709

best wishes

**Comment by brianmay** [comment]
I believe the finished version was in #245. Closing this.
