### ISSUE TITLE
Two roles with admin in project

### ISSUE THREAD

**Issue by SalahAdDin** [django-guardian/django-guardian#256]
Good Nights, this is a question, not a issue.

I need have to user's types: a default admin in django, and a author.
Default admin have a aditional permission: can publish a news.
And for author user i have the next constrains:
 - Can't publish news.
- Can't create other users
- Can't create other topics or subtopics
- Can create a new, but, only can edit or delete his own news, no other user's news.

I talked with other friend and he say me that i need per-objetcs permissions, but, i don't know how do this.

Can you help me?

**Comment by brianmay** [comment]
I see this is a support request dating from 2014, so probably the requester has moved on to other things by now. So I am going to close this ticket.

I will comment however and say this task doesn't sound like you need per object permissions or Guardian. You just need to create an author group, assign the required permissions to this group, and then assign the required users to this group. Then it is up to the views to check the permissions as required.

It is possible in the above I made incorrect assumptions about the problem, in which case my answer may not be correct.

**Comment by SalahAdDin** [comment]
@brianmay yes man, these it's the answer, thank you for all, i hope that i was a problem for you.
