### ISSUE TITLE
User.post_save() DoesNotExist: Permission matching query does not exist.

### ISSUE THREAD

**Issue by rizumu** [django-guardian/django-guardian#258]
I have a simple post_save method on my custom User class, Django 1.7. The problem is that migrate (previously syncdb), Guardian's AnonymousUser creation is attempted before the Permissions are in the database, resulting in a Permission DoesNotExist error.
```
@receiver(post_save, sender=User)
def user_post_save(sender, **kwargs):
    """
    Create a Profile instance for all newly created User instances. We only
    run on user creation to avoid having to check for existence on each call
    to User.save.
    """
    user, created = kwargs["instance"], kwargs["created"]
    if created:
        from profiles.models import Profile
        profile = Profile.objects.create(pk=user.pk, user=user, creator=user)
        assign_perm("change_user", user, user)
        assign_perm("change_profile", user, profile)
```
I have simply changed it to  `if created and user.pk != -1:` or `if created and user.pk != settings.ANONYMOUS_USER_ID` and given the logic of my project the AnonymousUser doesn't need permissions anyhow. However, maybe there is something deeper going on for you to look at. Just wanted to bring it to you attention as I found it curious and this may be of help to others, even if this is a non-issue.

**Comment by brianmay** [comment]
Not sure what else guardian can do here. Possibly the documentation could be improved?
