### ISSUE TITLE
PermissionRequiredMixin does not check permissiosn against an object

### ISSUE THREAD

**Issue by ramast** [django-guardian/django-guardian#259]
Hey Guys,
According to guardian documentation PermissionRequiredMixin will check the permission against the object specified by the function get_object or attribute self.object if neither specified it will check if the user has the permission globally
https://pythonhosted.org/django-guardian/api/guardian.mixins.html
but when I check the code it seems this Mixin only check the global permission and never call get_object, debugging my code also proved that.
am I missing something or is this a bug?

I can fix it and upload a patch but need to verify its really a bug
Tested version: 1.2.4

**Comment by aidanlister** [comment]
For me it's checking the object permission and ignoring the fact that the user has global permissions?

**Comment by brianmay** [comment]
No response; closing. Can be reopened if required. Also see #380.
