### ISSUE TITLE
Update permissions in model

### ISSUE THREAD

**Issue by MagdaN** [django-guardian/django-guardian#260]
Hi there,

I have a model with a an m2m with auth.Group and a permission like that:

```python
    class Document(models.Model):
    (...)
    allowed_groups = models.ManyToManyField(Group,...)
    (...)
    class Meta:
        permissions = (('view_document', 'Can view document'))
```

I use django-guardian for per object permissions. I added a post_save-method (earlier it was in the save-method of that model) for that model to update the group permissions depending on the field document.allowed_groups. It looks like that (simplified):

```python
def permissions_post_save(sender, instance=False, **kwargs):
    document = Document.objects.get(pk=instance.pk)
    viewright = 'view_document'
    (...)
    for group in document.allowed_groups:
        assign_perm(viewright, group, document) 
```

My Problem now is, that this never gets saved to the Database. I have the same code in my save-method for my form and it works perfectly fine. What am I doing wrong?

**Comment by brianmay** [comment]
Anything could be wrong here. Not enough information given to tell what.

Are you sure you connected the `permissions_post_save` method correctly up with the Django signal? Try adding some print statements? Make sure `assign_perm` is getting called?

**Comment by brianmay** [comment]
Not enough information to tell what is wrong. Closing.
