### ISSUE TITLE
Another RemovedInDjango18Warning for Options.module_name

### ISSUE THREAD

**Issue by mishu-** [django-guardian/django-guardian#274]
Here is the warning that I get:
```
/Library/Python/2.7/site-packages/guardian/admin.py:95: RemovedInDjango18Warning: Options.module_name has been deprecated in favor of model_name
  info = self.model._meta.app_label, self.model._meta.module_name
```
I use: 
`django-guardian==1.2.4`

**Comment by wldcordeiro** [comment]
This is also present here: https://github.com/lukaszb/django-guardian/blob/devel/guardian/admin.py#L107

**Comment by troygrosfield** [comment]
@lukaszb, the change for this is super simple and it would be nice to get this on the radar since django 1.8 alpha is already out.  Thanks in advance.

**Comment by troygrosfield** [comment]
This is now breaking for django 1.8.  Also logged at #303.

**Comment by Karlheinzniebuhr** [comment]
this is now breaking in django please update the package

**Comment by brianmay** [comment]
I believe this is fixed and should be closed.
