### ISSUE TITLE
BUG - Admin Panel not working in Django 1.7

### ISSUE THREAD

**Issue by vukasin0** [django-guardian/django-guardian#280]
As per documentation: 

>http://pythonhosted.org//django-guardian/userguide/admin-integration.html

    And thats it. We can now navigate to change post page and just next to the history link 
    we can click Object permissions button to manage row level permissions.

And here is error printed on Stdout:

    /usr/local/lib/python2.7/dist-packages/guardian/admin.py:95: 
     RemovedInDjango18Warning:Options.module_name has been deprecated in favor of model_name
    
    info = self.model._meta.app_label, self.model._meta.module_name

**Comment by wldcordeiro** [comment]
This isn't an error, it's a warning and shouldn't block you from using the admin.

**Comment by Karlheinzniebuhr** [comment]
this is now breaking in django 1.8 please update the package

**Comment by brianmay** [comment]
I believe this has been fixed, and should be closed.
