### ISSUE TITLE
Milestone v1.2 and 2.0?

### ISSUE THREAD

**Issue by dmr** [django-guardian/django-guardian#282]
I'm a big fan of django-guardian and have been using it for quite a while. Today I was wondering what happened in the project since the last time I checked and I don't understand what the current project status is.
http://django-guardian.readthedocs.org/en/v1.2/develop/changes.html

What happened in the releases since 1.2?
What is the plan for 2.0 and how can I help?

**Comment by brianmay** [comment]
Think perhaps you are getting confused with #355 - you were looking at the v1.2 documentation, so it won't have more recent changes. For the latest stable changes see:

http://django-guardian.readthedocs.org/en/stable/develop/changes.html
