### ISSUE TITLE
ImportError: cannot import name GuardedModelAdmin if Django DEBUG = False

### ISSUE THREAD

**Issue by CurlingGeek** [django-guardian/django-guardian#290]
If:

1. You have your MyModel and MyModelAdmin classes both in your models.py, and
2. Django DEBUG = False

Then when accessing Django you get an error.

  File "./myapp/models.py", line 3, in <module>
    from guardian.admin import GuardedModelAdmin
ImportError: cannot import name GuardedModelAdmin

This doesn't happen if DEBUG = True. The workaround is simple: move the class MyModelAdmin(GuardedModelAdmin) out of models.py into admin.py like the documentation says you should.

Mostly sharing in case someone else hits this issue: because it works with Debug = True, it presented as if things worked in development, but failed on the production server.

**Comment by brianmay** [comment]
This doesn't appear to be a bug in django-guardian. I am guessing there might have been a circular import loop somewhere, although there is not enough information to confirm this. It might also have been specific to the Django version you were using. If you can think of improvements to the documentation they are welcome. For now, closing.
