### ISSUE TITLE
Move project to a community driven development

### ISSUE THREAD

**Issue by wldcordeiro** [django-guardian/django-guardian#310]
@lukaszb It seems you've been pretty busy with this project. I suggest creating a Github organization (say DjangoGuardianCommunity or something) and then transferring the ownership of this repo to the org and adding some contributors to it and giving them commit access. This way development doesn't stagnate in the face of new versions of Django 1.8.

**Comment by lukaszb** [comment]
That's a very good suggestion. In fact I've been thinking about this for a while now. And will definitely do that soon

**Comment by frwickst** [comment]
:+1:

**Comment by scholtalbers** [comment]
:+1:

**Comment by mcgeeco** [comment]
:+1:

**Comment by mcastle** [comment]
:+1:

**Comment by lukaszb** [comment]
First stage done. Now I'm going to send an email with call for help to some of contributors

**Comment by Wtower** [comment]
:+1:

**Comment by naranjia** [comment]
How is this coming along? It would be nice to get some pull requests merged into a new release as 1.3 has some very critical bugs in it.

**Comment by lukaszb** [comment]
@brianmay officially joined django-guardian team. He has contributed a LOT in the last couple of releases, in both code and reviews.
