### ISSUE TITLE
When merging querysets using 'or', you cannot have extra(select=...) on both sides.

### ISSUE THREAD

**Issue by Codigy** [django-guardian/django-guardian#316]
When merging querysets using 'or', you cannot have extra(select=...) on both sides.

Error in method get_objects_for_user If queryset extra and use_groups=True.

```
    objects = queryset.filter(pk__in=values)
    if use_groups:
        values = groups_obj_perms_queryset.values_list(fields[0], flat=True)
        if group_model.objects.is_generic():
            values = list(values)
        objects |= queryset.filter(pk__in=values)
```

**Comment by Codigy** [comment]
A possible solution?
https://github.com/Codigy/django-guardian/commit/c239df85c423d1c747a773d3cb18f341d23c1ef6

**Comment by brianmay** [comment]
Sorry, not sure I understand the problem you are talking about. Are you getting an error from the above code? Or is it returning incorrect results?

The code has changed significantly, so am going to close on the assumption that it was fixed. If this is not the case, please let me know.
