### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by xordoquy** [django-guardian/django-guardian#324]
I started working on the Django REST Framework compatibility with Django 1.9
Here's one of the issue we had that relates to django-guardian:

```
.tox/py34-djangomaster/lib/python3.4/site-packages/guardian/management/__init__.py:46: in <module>
    signals.post_syncdb.connect(create_anonymous_user, sender=guardian_app,
E   AttributeError: 'module' object has no attribute 'post_syncdb'
```

**Comment by brianmay** [comment]
Fixed in cf1c818d30abaa649eae2e5697e862c168d8b166. All tests pass in the latest version of devel for Django 1.9
