### ISSUE TITLE
Filter queryset in guardian admin by user raises error

### ISSUE THREAD

**Issue by VictorCoder123** [django-guardian/django-guardian#329]
I have something I don't quite understand when using django-guardian admin integration. My purpose is to get a list of objects owned by a specific user, so I set self.user_can_access_owned_objects_only = True. 

What I don't understand is how the queryset can be filter by 'user', which is not a model field and raises error in my case.

def get_queryset(self, request):
 
        if request.user.is_superuser:
            return qs

        if self.user_can_access_owned_objects_only:
            filters = {self.user_owned_objects_field: request.user}
            qs = qs.filter(**filters)

Did I miss something in the configuration?

**Comment by gregorvolkmann** [comment]
You have to set user_owned_objects_field to your models field, representing the user who owns the object. In my case my Model's field was named 'owner'

My code looks like this:

    class GuardedDeveloperModelAdmin(GuardedModelAdmin):
        user_can_access_owned_objects_only = True
        user_owned_objects_field = 'owner'

**Comment by brianmay** [comment]
Looks like this was a non-bug. Or possibly a documentation issue. Pull requests to fix documentation appreciated. Closing this for now.
