### ISSUE TITLE
Checking global permissions and row level perms

### ISSUE THREAD

**Issue by aidanlister** [django-guardian/django-guardian#332]
I saw this marked as fixed (https://github.com/lukaszb/django-guardian/issues/49) but I still need to do my perm checks like this:

````
if not self.account.has_perm('clients.view_client_dashboard') and not \
    self.account.has_perm('clients.view_client_dashboard', self.instance):
````

... is that supposed to work that way?

**Comment by brianmay** [comment]
Sorry, could you please elaborate on the problem? Not sure I understand.

I think that you are claiming that #49 hasn't been fixed, and `user.has_perm("perm", obj)` is still not checking the global permissions?

Is the correct?

**Comment by brianmay** [comment]
Unfortunately there is no reference inside #49 to the change that supposedly fixed this.

**Comment by brianmay** [comment]
Looks like another place where we get confused with global and per object permissions. We need to draft a standard of what should happen, and then stick to it.

**Comment by brianmay** [comment]
Moving to #380.
