### ISSUE TITLE
Consequences of direct foreign keys on orphaned object permissions

### ISSUE THREAD

**Issue by ad-m** [django-guardian/django-guardian#335]
Hello,

I read section "Orphaned object permissions" and "Direct foreign keys". 

I am would like ask about consequences of direct foreign keys (DFK). In my mind using DFK should avoid creating orphaned object permissions. Please correct, if I'm wrong.

I think this should be noted in docs.

Greetings,

**Comment by p-himik** [comment]
Has this really been tested? I installed django-guardian using pip a few days ago, created models and DFKs, added some objects with permissions and written a script that ensures that every model has a view permission. After playing around I decided to remove most of the data and turn what's left to fixtures. So I removed users and django admin panel and some other objects, and ran manage.py dumpdata. It contained a lot of django-guardian records, so I ran clean_orphan_obj_perms which returned 68, not 0.

**Comment by ad-m** [comment]
Are you sure do you use DFK? Which database backend do you use? Do you can shows your source code of DFK model? Do you can provide dump database schema (database dump without data)? Which way do you remove your objects?

If you use DFK then you create direct foreign key from "django-guradian model" to object model (see ```ProjectUserObjectPermission``` in https://django-guardian.readthedocs.org/en/v1.4.4/userguide/performance.html#direct-foreign-keys ). There is should exists constraint to remove all related objects.

**Comment by p-himik** [comment]
Sorry, there must be some error on my side, although I don't really see what I could do wrong. I just tried to create a new app, completely by the book - and everything worked like a charm.
