### ISSUE TITLE
Direct ForeignKey in Django 1.8

### ISSUE THREAD

**Issue by pgeez** [django-guardian/django-guardian#337]
per Django 1.8, the manager returned by `obj._meta.get_all_related_objects()` has changed (see: https://docs.djangoproject.com/en/1.8/releases/1.8/) such that permission objects must now be referenced by the `related_model` field instead of the `model` field (https://github.com/django-guardian/django-guardian/blob/devel/guardian/utils.py#L153). This change affects `get_obj_perms_model(...)` and has the consequence that Direct Foreign Key permission models are no longer detected.

**Comment by naranjia** [comment]
#319 should fix this.

**Comment by brianmay** [comment]
This was fixed in #359, see bac7c403062e81594a2ebed31562e72e83004dff
