### ISSUE TITLE
with_superuser flag should not default to True

### ISSUE THREAD

**Issue by zanderle** [django-guardian/django-guardian#341]
In `get_objects_for_user` the `with_superuser` flag defaults to `True`. This really shouldn't be the case. It makes it very easy to expose all data by accident. This feature is something that should be set specifically to True, as it can be a security vulnerability.

It also shouldn't default to `True` because of upgrading from older versions. It was added only recently and it is very easy to miss when upgrading - it is necessary to add `with_superuser=False` to each and every instance of `get_objects_for_user` and if a developer misses it, they are possibly exposing a lot of data.

**Comment by ryanisnan** [comment]
+1

**Comment by GNewc** [comment]
Um... no doubt! This just exposed data to people that had NO permission to see it... except that this default flag just made them all *superuser*.

**Comment by brianmay** [comment]
If I am reading the code correctly, I think `with_superuser` only returns all data if the user is a superuser:

```python
if with_superuser and user.is_superuser:
    return queryset
```

Does this help with your concerns?

**Comment by lukaszb** [comment]
@zanderle as @brianmay mentioned, data should be exposed only for superusers. This is actually to allow to hide content away from superusers. Closing now, let us know if you thing we can clarify that somehow.

**Comment by zanderle** [comment]
@lukaszb the docstring documentation should be clearer then:

```
:param with_superuser: if ``True`` returns the entire queryset if not it will
    only return objects the user has explicit permissions. Default is ``True``.
```

This really doesn't reflect what the code does...

**Comment by brianmay** [comment]
Reopening so we can fix the documentation.

**Comment by brianmay** [comment]
@lukaszb Not sure I understand why `accept_global_perms` has no affect unless `with_superuser` is True and `user.is_superuser` is False???

Shouldn't we be able to do `accept_global_perms` processing where `with_superuser` is False? Or have I misunderstood something?

**Comment by brianmay** [comment]
I am inclined to think that `accept_global_perms` is should work even when `with_superuser` is False. However it seems to be documented this way, so I guess it stays.

> Note, that if with_superuser is False, accept_global_perms will be ignored, which means that only
> object permissions will be checked! Default is ``True``.
