### ISSUE TITLE
guardian dies during create_anonymous_user

### ISSUE THREAD

**Issue by mwidman** [django-guardian/django-guardian#352]
In Django 1.7 or above, I cannot get django-guardian 1.3 to create an anonymous user during the "migrate" command.

It attempts to do so immediately after the auth_user table is created but does not supply an email address which is a non-null field by default. So the whole thing dies on:

django.db.utils.IntegrityError: (1048, "Column 'email' cannot be null")

**Comment by brianmay** [comment]
Some more details would be really useful here. How are you trying to create an anonymous user? What is the full stack trace of the error?

**Comment by brianmay** [comment]
If you are talking about guardian automatically creating the anonymous user, I am still a bit puzzled. What happens for me, at least for the tests, is that email automatically gets given an empty string value, and this works.

Possibly this has changed, I am looking at the latest git version, I am doubtful however.

The full stack trace might help.

**Comment by brianmay** [comment]
No response; closing.
