### ISSUE TITLE
Is pep8 compatibility necessary for this project?

### ISSUE THREAD

**Issue by staranjeet** [django-guardian/django-guardian#365]
The project does not complies to pep8. 

I can work on this and submit a PR.

**Comment by swistakm** [comment]
It seems that pep-8 is your hobby @staranjeet. Isn't it?

**Comment by staranjeet** [comment]
@swistakm : No. Just doing pep8, I can easily have a go through the code and it also helps in maintaining the readability for the project. Also,
>code is read much more often than it is written.

**Comment by brianmay** [comment]
I would be willing to look at and merge any pull request for PEP8. Please make sure you don't make any other changes other then the PEP8 changes (or at least separate other changes into separate commits).

**Comment by lukaszb** [comment]
Just make sure to bump line length a little (to, let's say 99 characters). Also, docstrings should stay Django-like (no one line docstrings).

**Comment by staranjeet** [comment]
Ok, I will keep the line length to 99 characters and submit PR so that the diff becomes easy to review. I will fix 1 or 2 files in each PR.

**Comment by brianmay** [comment]
Think we can close this now, right? Was merged #367. If not, will reopen.
