### ISSUE TITLE
Guardian and Django system checks

### ISSUE THREAD

**Issue by Wtower** [django-guardian/django-guardian#369]
I was wondering, would it be neat to write a couple of custom [system checks](https://docs.djangoproject.com/en/1.7/topics/checks/), now that Django allows it.

Something like to check that Guardian backend is in the authentication backends setting and that an anonymous user id has been set.

If you agree I would be glad to help.

**Comment by lukaszb** [comment]
@Wtower cool idea, +1 from me :)

**Comment by Wtower** [comment]
Great. This is ready:

https://github.com/Wtower/django-guardian/tree/system-checks

But before a merge request: first, I could not run tests under `example_project` because of #364 . When trying to run on a different project, I get a `django.db.utils.OperationalError: no such table: guardian_project` so obviously I miss something but can't get around it for the time.

Second, a question: this feature would require `django.core.checks`, which is a feature of Django 1.7. My understanding is that we currently support 1.5+ for Guardian. Is this correct? If so, how do we deal with this?

**Comment by brianmay** [comment]
See #350, already a proposal to drop support for Django < 1.7 - maybe this might be the trigger that actually does this.

**Comment by Wtower** [comment]
Ok, both issues settled for me. The one test that I have added passed and covers the code changes. Proceeding with a merge request.

**Comment by brianmay** [comment]
I merged the change, so closing this ticket.
