### ISSUE TITLE
Warnings `RemovedInDjango110Warning` with Django 1.9

### ISSUE THREAD

**Issue by Wtower** [django-guardian/django-guardian#370]
The following warnings appear in a Django 1.9 test run:

    ...s/django-guardian/guardian/utils.py:153: RemovedInDjango110Warning: 'get_all_related_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'
      for attr in obj._meta.get_all_related_objects():

    /django-guardian/guardian/testapp/tests/test_orphans.py:31: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    /django-guardian/guardian/utils.py:164: RemovedInDjango110Warning: 'get_field_by_name is an unofficial API that has been deprecated. You may be able to replace it with 'get_field()'
      fk = model._meta.get_field_by_name('content_object')[0]

    /django-guardian/guardian/testapp/tests/test_orphans.py:33: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    /django-guardian/guardian/testapp/tests/test_other.py:126: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    /django-guardian/guardian/testapp/tests/test_other.py:37: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    /django-guardian/guardian/testapp/tests/test_other.py:128: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    /django-guardian/guardian/testapp/tests/test_other.py:130: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    /django-guardian/guardian/testapp/tests/test_other.py:39: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    /django-guardian/guardian/testapp/tests/test_other.py:41: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    /django-guardian/guardian/utils.py:153: RemovedInDjango110Warning: 'get_all_related_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'
      for attr in obj._meta.get_all_related_objects():

    /django-guardian/guardian/utils.py:164: RemovedInDjango110Warning: 'get_field_by_name is an unofficial API that has been deprecated. You may be able to replace it with 'get_field()'
      fk = model._meta.get_field_by_name('content_object')[0]

    /django-guardian/guardian/testapp/tests/test_other.py:247: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    /django-guardian/guardian/utils.py:153: RemovedInDjango110Warning: 'get_all_related_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'
      for attr in obj._meta.get_all_related_objects():

    /django-guardian/guardian/utils.py:153: RemovedInDjango110Warning: 'get_all_related_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'
      for attr in obj._meta.get_all_related_objects():

    /django-guardian/guardian/testapp/tests/test_custompkmodel.py:18: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    ................./home/gkarak/.virtualenvs/django-guardian/local/lib/python2.7/site-packages/django/core/management/base.py:577: RemovedInDjango110Warning: NoArgsCommand class is deprecated and will be removed in Django 1.10. Use BaseCommand instead, which takes no arguments by default.
      RemovedInDjango110Warning

    ....../django-guardian/guardian/utils.py:164: RemovedInDjango110Warning: 'get_field_by_name is an unofficial API that has been deprecated. You may be able to replace it with 'get_field()'
      fk = model._meta.get_field_by_name('content_object')[0]

    /django-guardian/guardian/testapp/tests/test_tags.py:26: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    ../home/gkarak/.virtualenvs/django-guardian/local/lib/python2.7/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
      "unable to load templates.", RemovedInDjango110Warning)

    ......./django-guardian/guardian/utils.py:164: RemovedInDjango110Warning: 'get_field_by_name is an unofficial API that has been deprecated. You may be able to replace it with 'get_field()'
      fk = model._meta.get_field_by_name('content_object')[0]

    /django-guardian/guardian/testapp/tests/test_forms.py:14: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    /home/gkarak/.virtualenvs/django-guardian/local/lib/python2.7/site-packages/django/shortcuts.py:45: RemovedInDjango110Warning: The context_instance argument of render_to_string is deprecated.
      using=using)

    ........../django-guardian/guardian/testapp/tests/test_admin.py:45: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    /django-guardian/guardian/admin.py:116: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      name='%s_%s_permissions_manage_group' % info),

    /django-guardian/guardian/testapp/tests/urls.py:14: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      (r'^admin/', include(admin.site.urls)),

    /django-guardian/guardian/testapp/tests/urls.py:24: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      (r'^permission_required/', testClassRedirectView.as_view()),

    /home/gkarak/.virtualenvs/django-guardian/local/lib/python2.7/site-packages/django/conf/urls/__init__.py:89: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got django.contrib.auth.views.login). Pass the callable instead.
      t = url(prefix=prefix, *t)

    /django-guardian/guardian/testapp/tests/test_decorators.py:370: RemovedInDjango110Warning: Reversing by dotted path is deprecated (django.contrib.auth.views.login).
      self.assertRedirects(response, reverse(settings.LOGIN_URL) + "?next=" + view_url)

    /django-guardian/guardian/admin.py:116: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      name='%s_%s_permissions_manage_group' % info),

    /django-guardian/guardian/testapp/tests/urls.py:14: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      (r'^admin/', include(admin.site.urls)),

    /django-guardian/guardian/testapp/tests/urls.py:24: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      (r'^permission_required/', testClassRedirectView.as_view()),

    /home/gkarak/.virtualenvs/django-guardian/local/lib/python2.7/site-packages/django/conf/urls/__init__.py:89: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got django.contrib.auth.views.login). Pass the callable instead.
      t = url(prefix=prefix, *t)

    /django-guardian/guardian/admin.py:209: RemovedInDjango110Warning: The current_app argument of RequestContext is deprecated. Set the current_app attribute of its request instead.
      context, RequestContext(request, current_app=self.admin_site.name))

    /home/gkarak/.virtualenvs/django-guardian/local/lib/python2.7/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
      "unable to load templates.", RemovedInDjango110Warning)

    /home/gkarak/.virtualenvs/django-guardian/local/lib/python2.7/site-packages/django/shortcuts.py:45: RemovedInDjango110Warning: The context_instance argument of render_to_string is deprecated.
      using=using)

    ....................../django-guardian/guardian/testapp/tests/test_core.py:30: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    /django-guardian/guardian/testapp/tests/test_core.py:153: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    /django-guardian/guardian/testapp/tests/test_core.py:155: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    /django-guardian/guardian/admin.py:308: RemovedInDjango110Warning: The current_app argument of RequestContext is deprecated. Set the current_app attribute of its request instead.
      context, RequestContext(request, current_app=self.admin_site.name))

    ........./django-guardian/guardian/testapp/tests/test_core.py:30: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    /django-guardian/guardian/testapp/tests/test_shortcuts.py:335: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    /django-guardian/guardian/testapp/tests/test_shortcuts.py:337: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    /django-guardian/guardian/testapp/tests/test_shortcuts.py:804: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    /django-guardian/guardian/testapp/tests/test_shortcuts.py:806: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    /django-guardian/guardian/testapp/tests/test_shortcuts.py:808: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    .............../django-guardian/guardian/testapp/tests/test_shortcuts.py:415: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    ......./django-guardian/guardian/testapp/tests/test_shortcuts.py:448: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    ......./django-guardian/guardian/testapp/tests/test_shortcuts.py:171: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    /django-guardian/guardian/testapp/tests/test_shortcuts.py:173: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    ....................../django-guardian/guardian/testapp/tests/test_core.py:30: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    ....../django-guardian/guardian/testapp/tests/test_mixins.py:36: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='fake-for-guardian-tests')

    ................../django-guardian/guardian/admin.py:116: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      name='%s_%s_permissions_manage_group' % info),

    /django-guardian/guardian/testapp/tests/urls.py:14: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      (r'^admin/', include(admin.site.urls)),

    /django-guardian/guardian/testapp/tests/urls.py:24: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      (r'^permission_required/', testClassRedirectView.as_view()),

    /home/gkarak/.virtualenvs/django-guardian/local/lib/python2.7/site-packages/django/conf/urls/__init__.py:89: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got django.contrib.auth.views.login). Pass the callable instead.
      t = url(prefix=prefix, *t)

    ............./django-guardian/guardian/testapp/tests/test_shortcuts.py:435: RemovedInDjango110Warning: ContentType.name field doesn't exist any longer. Please remove it from your code.
      app_label='guardian-tests')

    ....................................../django-guardian/guardian/admin.py:255: RemovedInDjango110Warning: The current_app argument of RequestContext is deprecated. Set the current_app attribute of its request instead.
      context, RequestContext(request, current_app=self.admin_site.name))

    .................
    ----------------------------------------------------------------------
    Ran 220 tests in 4.352s

    OK (skipped=1)

Relevant issue #364 .

**Comment by brianmay** [comment]
travis-ci tests only reports one warning; however this is against 1.9b1, need to update that to use 1.9.0 now. Just looking at that now.

**Comment by brianmay** [comment]
How do I enable the `RemovedInDjango110Warning` warnings?  Seem to remember these are disabled by default.

**Comment by brianmay** [comment]
Disregard what I said before, I only seem to be getting one warning with Django 1.9.0. See https://travis-ci.org/django-guardian/django-guardian/jobs/95265271 - not sure why you are getting more warnings then me.

**Comment by brianmay** [comment]
I fixed the one warning I saw. f03ad3a99e58531308bfc5f76510673eed467b7e

**Comment by Wtower** [comment]
I really got no clue why this happens. If there would be a `PYTHONWARNINGS="ignore"` env then you wouldn't get even a single one. I don't recall any other condition under which warnings are hidden. I get similar warnings with other projects that I upgraded to 1.9.

**Comment by brianmay** [comment]
Looks like I need to use -Wd to get all warnings. Which is very verbose, I get a lot of `RemovedInDjango20Warning` warnings too.

**Comment by Wtower** [comment]
Nice. Now I remember something in the back of my head about this option (something about the wall) but I can't find any documentation about it atm. Anyway, I will try to tackle the warnings if you want me too bit by bit.

**Comment by brianmay** [comment]
Any help fixing the warnings will be appreciated.

Thanks!

**Comment by Wtower** [comment]
Nice one, many warnings went off. Unfortunately I still get many warnings, so I don't think this is closed. I am bit hands-full these days but I will look into this.

**Comment by Wtower** [comment]
Almost finished. I will create a pull request very soon. The remaining warnings after that should be present in Django core only and hopefully will be tackled by 1.9.1:

    .virtualenvs/django-guardian3/lib/python3.4/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.

    .virtualenvs/django-guardian3/lib/python3.4/site-packages/django/shortcuts.py:45: RemovedInDjango110Warning: The context_instance argument of render_to_string is deprecated.

    virtualenvs/django-guardian3/lib/python3.4/site-packages/django/core/management/base.py:577: RemovedInDjango110Warning: NoArgsCommand class is deprecated and will be removed in Django 1.10. Use BaseCommand instead, which takes no arguments by default.

**Comment by Wtower** [comment]
Fixed in #379

**Comment by Ashaba** [comment]
do not pass a context_instance, or any deprecated argument, using render_to_response.
`context_instance=RequestContext(request)`

**Comment by ashokpal100** [comment]
ok
