### ISSUE TITLE
Please fix API reference docs for 1.3.2

### ISSUE THREAD

**Issue by MadWombat** [django-guardian/django-guardian#374]
The docs only have names of entities and no actual information

**Comment by brianmay** [comment]
Have fixed this for the "lastest" version. Can't fix it for 1.3.2, sorry as fix requires a requirements.txt file to be added to the source. You may have to click reload to get new pages (or clear your cache).

**Comment by MadWombat** [comment]
https://django-guardian.readthedocs.org/en/stable/api/guardian.shortcuts.html

still shows only names and no content

**Comment by brianmay** [comment]
Like I said, I can't actually fix 1.3.2 with readthedocs, because that source code has already been published and I can't make changes to it.

**Comment by brianmay** [comment]
I am hoping that readthedocs might notice that 1.4.1 has been published, and build the documentation for that version sometime. So far it isn't listing it however.

**Comment by MadWombat** [comment]
I only mentioned because my PIP just upgraded to 1.4, so I assumed that that was the latest stable

**Comment by brianmay** [comment]
1.4.1 is the latest stable.

**Comment by MadWombat** [comment]
Yay. Thanks for clarifying.
