### ISSUE TITLE
Django1.9 change view url has changed.

### ISSUE THREAD

**Issue by rhblind** [django-guardian/django-guardian#376]
Hi,

Django1.9 has changed the `change view` url in admin. This makes the [url pattern](https://github.com/django-guardian/django-guardian/blob/devel/guardian/admin.py#L100-L110) specified in `GuardedModelAdminMixin` invalid.

The url pattern is changed from `/admin/<app>/<model>/<pk>/` to `/admin/<app>/<model>/<pk>/change/`.

See the [Django Changelog](https://docs.djangoproject.com/en/1.9/releases/1.9/#django-contrib-admin) for details.

**Comment by brianmay** [comment]
Sorry, not sure I understand the problem.

There was a bug in django-guardian in that the URLs to change the permissions were incorrectly generated, however this has already been fixed in the devel branch: 9818331aa34bea625eeec9424b9998b2b260f234

For me, all the links work after this fix.

**Comment by rhblind** [comment]
Ah, alright. I'm running v1.3.2 from pypi.
Never mind then =)
