### ISSUE TITLE
Trying to understand guardian in the context of my project

### ISSUE THREAD

**Issue by aronadaal** [django-guardian/django-guardian#378]
Hi there,
I'm still trying to understand the principles behind guardian and how I can benefit from it in my django project.

Ok, I'll give you a short overview of the project I'm working on. I'm programming an issue-tracker for a specialized project, so 'cots'-bug/issue tracker could not satisfy our needs.

First, we have User in the system. Nothing special, the django standard user. Next we have projects as an organisational structure as well as three user-groups: observer, editor, manager the users can belong to. And finally there are the issues, which are bound to projects (1:many).

The observer can only view a project as well as the issues inside. Nothing else. The editor can edit the issues and work with them. The manager is the most privileged one. He can create subprojects, close issues and import issues into a project.

Hope you understand the basic concept behind my project.

Currently I have three M2M tables (observer, editor, manager) binding a user to a group in a project. Then I wrote several permission checking functions for all kind of needs:
- is_user_manager_byUser(self, user) - true/false (one function for every group)
- def get_groups(user) - return all groups of user
- def get_min_group(user) - return the minimal group of the complete systems
- def has_min_group_editor(user, project) - true/false (one function for every group)
- get_role(user, project) - return the group which the user belongs to in the given project

My permission system brings a lot of code overhead in to the project which I want to get rid off. So I'm thinking about using guardian but I have no really good idea how to use it well!

Things I would like to know but I couldn't find inside the docs:
- How can I get all groups a user belongs to in for example a project?
- Do I really have to build unique groups per project? This means 3*n db-tables for each project on top.
- Is there a way to work with groups instead of granular permissions?
- ...

Sorry for all the text and only three "simple" questions but I have a lot of question marks behind the concepts in the context of my project.

Thanks in advance,
aronadaal

**Comment by brianmay** [comment]
Have a look at the latest development documentation: 
http://django-guardian.readthedocs.org/en/latest/

Does this help answer your questions?

Note that django-guardian has some performance issues with some operations. Read through the list of open issues.

For another solution that does things in a very different way, have a look at the django-rules project.

To answer your questions above, to the best of my knowledge:

* Groups are just the same as in standard Django. That is I think you should be able to access `user.groups.all()` to access all groups for user.

* With django-guardian you can assign the permissions to the projects, so you only need three permissions - e.g. can_observe_project, can_edit_project, and can_manage_project,

* Permissions can be assigned to any objects, including group objects.

Hope this helps.

**Comment by brianmay** [comment]
I am going to close this for now. If you can think of any way of improving the documentation, patches are welcome.
