### ISSUE TITLE
tests broken with Mysql and Django 1.9.0

### ISSUE THREAD

**Issue by brianmay** [django-guardian/django-guardian#385]
See https://travis-ci.org/django-guardian/django-guardian/jobs/100522453

**Comment by brianmay** [comment]
Looks like these problems don't happen with Django 1.9.1; so I suspect a problem with Django 1.9.0

**Comment by ad-m** [comment]
What do you think about range definition of version in TravisCI?
Eg.
```
dj18: Django>=1.8,<1.9
dj17: Django>=1.7,<1.8
```
In this way works fg. django-grappeli, django-filebrowser and all of my projects.
I can prepare required patch.

**Comment by brianmay** [comment]
Yes, that might be better.

Assuming it picks the latest version by default.

**Comment by brianmay** [comment]
After applying d4dd32c296f918abf426a3d6146337bd65a67697 to use Django 1.9.1 the mysql tests pass.

**Comment by ad-m** [comment]
@brianmay , here is the django issues which looks similiar : https://code.djangoproject.com/ticket/25882 :smile:

**Comment by brianmay** [comment]
Yes, does look like it. Thanks for the research. Closing this bug.
