### ISSUE TITLE
Hierarchy between permissions

### ISSUE THREAD

**Issue by mitar** [django-guardian/django-guardian#386]
It would be great to have support for hierarchy between permissions. So that you can have a higher level permission with lower level sub-permissions. So you could then assign the higher level permission, but user would get also all lower level permissions. If more lower level permissions are added to the higher level permissions, those permissions in effect for all users on all object with that higher level permission.

**Comment by brianmay** [comment]
Going to close this in favor of #23. Can be reopened if we find it is different.
