### ISSUE TITLE
Problem with installing version 1.4.0

### ISSUE THREAD

**Issue by dblenkus** [django-guardian/django-guardian#387]
I've tried to install `django-guardian` 1.4.0 into fresh a virtualenv but I got this error:
```
[domen@fedora ~]# pip install django-guardian
Collecting django-guardian
  Downloading django-guardian-1.4.0.tar.gz (296kB)
    100% |████████████████████████████████| 299kB 1.7MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-GHkmMl/django-guardian/setup.py", line 6, in <module>
        guardian = __import__('guardian')
      File "guardian/__init__.py", line 5, in <module>
        from . import checks
      File "guardian/checks.py", line 2, in <module>
        from django.core.checks import register, Tags, Warning
    ImportError: No module named django.core.checks
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-GHkmMl/django-guardian
````
I'm using Fedora 23, Python 2.7.10 and pip 7.1.2

**Comment by dblenkus** [comment]
Looks like you are [importing `guardian`in `setup.py`](https://github.com/django-guardian/django-guardian/blob/devel/setup.py#L6), which [imports `checks`](https://github.com/django-guardian/django-guardian/blob/devel/guardian/__init__.py#L5), which [imports `django`](https://github.com/django-guardian/django-guardian/blob/devel/guardian/checks.py#L2), which is not available yet.

**Comment by hellysmile** [comment]
+1 same issue, it is easy solve via manual installation of django, but bit tricky for example on heroku or any `pip install -r requirements.txt` based deploy

**Comment by brianmay** [comment]
I think I understand the problem. setup.py is suppose to ensure that django is the correct version, but fails before it can do it's job.

I think I might change this so setup.py doesn't import guardian. It does so this to retrieve the version number. My experience has shown this is error prone, as this ticket shows.

**Comment by brianmay** [comment]
Somehow this change broke the travis-tests for Python 3.x - still trying to understand why.

**Comment by brianmay** [comment]
Tests should be fixed again now. Fingers crossed.

**Comment by dblenkus** [comment]
Please create new release on pypi.

**Comment by ad-m** [comment]
:+1:

**Comment by brianmay** [comment]
That is the current plan; hope to make a new release tomorrow (UTC+11 timezone).

**Comment by dblenkus** [comment]
Thanks!

**Comment by brianmay** [comment]
Done.
