### ISSUE TITLE
Maximum line length

### ISSUE THREAD

**Issue by ad-m** [django-guardian/django-guardian#390]
Hello,

I would like ask about preferred max line height for this project? Is is very controversial question sometime, but it is important to choose, because I am going to prepare some PEP8 fixes. I do not see consistent rules in the project. 

I propose to adopt a decision package maintainer without repeating the discussion.

Greetings,

**Comment by brianmay** [comment]
Adam Dobrawy <notifications@github.com> writes:

> I would like ask about preferred max line height for this project? Is
> is very controversial question sometime, but it is important to
> choose, because I am going to prepare some PEP8 fixes. I do not see
> consistent rules in the project.

I generally use the PEP8 default except for a few specific files
(e.g. autogenerated Django migrations).

However for this project, see discussion in #365.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/
