### ISSUE TITLE
ImportError guardian: cannot import name register

### ISSUE THREAD

**Issue by maikkma** [django-guardian/django-guardian#392]
I get this error when django loads all applications. 
Requested: /srv/www/maikkma/targetor/env/bin/python /srv/www/maikkma/targetor/manage.py migrate --all --no-initial-data --settings=settings.local_settings

env/local/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 25
CODE:
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.template.base import TemplateDoesNotExist
from django.template.loader import BaseLoader
from django.utils._os import safe_join
from django.utils.importlib import import_module
from django.utils import six

if six.PY2:
    fs_encoding = sys.getfilesystemencoding() or sys.getdefaultencoding()
app_template_dirs = []
for app in settings.INSTALLED_APPS:
    try:
        mod = import_module(app)
    except ImportError as e:
        raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))

So, I think this register is django admin module? Somehow this import_module(app) will fail? What might be wrong? This issue come out with 19.12.2015 update.

**Comment by brianmay** [comment]
What version of Django do you have?

**Comment by maikkma** [comment]
1.6.1

**Comment by brianmay** [comment]
Unfortunately that is too old, django-guardian now requires at least Django 1.7 - see http://django-guardian.readthedocs.org/en/stable/installation.html

**Comment by maikkma** [comment]
Yes, I notice that too. Thanks!
