### ISSUE TITLE
CSS doesn't load in the latest and stable docs

### ISSUE THREAD

**Issue by MadWombat** [django-guardian/django-guardian#397]
Doc pages load without styles even though CSS files load.

**Comment by brianmay** [comment]
I have no idea why this is not working. I asked about it here: http://stackoverflow.com/questions/35470532/readthedocs-broken-how-to-fix

**Comment by brentc** [comment]
This issue is closed, but the docs are still broken.

**Comment by brianmay** [comment]
The latest documents are fine. I can't fix the stable documents until the next release.

http://django-guardian.readthedocs.org/en/latest/

**Comment by brentc** [comment]
Ah. Ok.
