### ISSUE TITLE
Documentation is missing styles

### ISSUE THREAD

**Issue by mitar** [django-guardian/django-guardian#404]
https://django-guardian.readthedocs.org/en/stable/

In Firefox and Chrome.

**Comment by brianmay** [comment]
Interesting issue number for this :-)

Issue has been fixed in latest, need a new release to fix stable.

http://django-guardian.readthedocs.org/en/latest/

**Comment by shanemgrey** [comment]
I noticed this the other day and was just about to open an issue too. 

@mitar must have waited for this #404 issue to be next in line...   :-)

**Comment by mitar** [comment]
Conspiracies all around. ;-)

**Comment by W7PEA** [comment]
Stable \ v1.4.1 is what's broken
https://django-guardian.readthedocs.org/en/stable/
https://django-guardian.readthedocs.org/en/v1.4.1/

Latest works:
https://django-guardian.readthedocs.org/en/latest/

**Comment by brianmay** [comment]
Will keep this open until the next release.

**Comment by brianmay** [comment]
Documentation confirmed working after new release. Closing.
