### ISSUE TITLE
error using with django 1.9

### ISSUE THREAD

**Issue by auvipy** [django-guardian/django-guardian#416]
File "/home/travis/build/chibisov/drf-extensions/.tox/django.1.9/lib/python3.4/site-packages/guardian/management/__init__.py", line 46, in <module>
    signals.post_syncdb.connect(create_anonymous_user, sender=guardian_app,
AttributeError: 'module' object has no attribute 'post_syncdb'

**Comment by ad-m** [comment]
Which django-guardian versions?

**Comment by auvipy** [comment]
1.3.x as 1.4 breaks more tests of the package

**Comment by ad-m** [comment]
See cf1c818d30abaa649eae2e5697e862c168d8b166 and https://github.com/django-guardian/django-guardian/commits/v1.4.0/guardian/management/__init__.py . Do you can upgrade django-guardian?

**Comment by ad-m** [comment]
Which django versions do you use?

**Comment by auvipy** [comment]
https://github.com/tomchristie/django-rest-framework/issues/4005

**Comment by ad-m** [comment]
tomchristie/django-rest-framework#4005 is another issue. Fixed in ```devel``` branch.
