### ISSUE TITLE
The removal of ANONYMOUS_USER_ID can brake code

### ISSUE THREAD

**Issue by frwickst** [django-guardian/django-guardian#422]
I just upgraded from 1.4.1 to 1.4.4 and found myself with some errors when I ran my tests.

Since I thought that this was a minor patch release (only bumping Y in x.x.Y) I upgraded first, ran the tests and then read the change notes. After reading the changes I noticed that you guys have removed `ANONYMOUS_USER_ID` in 1.4.2. Instead you use `ANONYMOUS_USER_NAME` (not `ANONYMOUS_DEFAULT_USERNAME` as stated in the change log) and then look up the `USERNAME_FIELD` of a model.

My test errors was that I was getting an anonymous user back in my results. The problem being that I no longer had a user with ID = -1, something that had been created for me since I had configured django-guardian with `ANONYMOUS_USER_ID = -1`. My query looked something like this get_user_model().objects.filter(id__gt=-1), something that no longer worked, since no user with and ID set to -1 was available any longer. The anonymous user will not get an ID of 1 (or whatever ID is set to be the first auto increment number).

So now I have a production server running where I have a user with ID = -1, but when running tests or running a new dev database there is no such user.

Ok, I can change my code to `.exclude(<USERNAME_FIELD>='AnonymousUser')` and that would solve my problem. But I will still be left with a user that has id -1 in production and one with (most likely) 1 in dev/tests. And what about migrations? It kinda sucks that I will now need to go back and change data migrations (where I use `.filter(id__gt=-1)`).

The idea behind the change:

> ...the database is free to pick an appropriate id that doesn't clash.

is probably a nice thought but by letting the database choose its own ids, you ended up breaking existing code.

I think that this change was breaking and the version should have been 1.5.0 not 1.4.2. 

The changes are made and I have a feeling they will stay that way and will just have to change my own code, but I just wanted to let you know that this was not just as simple as changing a line in the settings file.

**Comment by brianmay** [comment]
Your concerns have been noted.

I don't think any action is required. I could possibly add more detail in CHANGES.rst:

```
Don't use ANONYMOUS_USER_ID. Uses ANONYMOUS_DEFAULT_USERNAME and USERNAME_FIELD instead.
```

For now will close this issue.

Thanks for the report.
