### ISSUE TITLE
Django should not be in setup.py's install_requires

### ISSUE THREAD

**Issue by crccheck** [django-guardian/django-guardian#423]
If someone is installing django-guardian, it's safe to assume they have Django installed already. Putting Django in `install_requires` ends up causing more problem than it solves because of unexpected Django upgrades.

Similar discussion: https://github.com/caioariede/django-location-field/issues/47

**Comment by brianmay** [comment]
Sounds like this is different from the django-location field case: "Django isn't a dependency of location-field in any useful sense."  Django is a hard requirement for django-guardian.

Furthermore setuptools should not be touching Django if it already meets the requirement (Django >= 1.7). This is what happens with my tests.

Maybe you have an old/buggy version of setuptools? Or could it be that another package was getting installed at the same time that pulled in a specific version of Django?

Also see #420.

**Comment by brianmay** [comment]
No response; closing. Can reopen if required.

**Comment by andybak** [comment]
Hi,

For me the issue is specifically this: https://github.com/caioariede/django-location-field/issues/47#issuecomment-192703189

Quite often I want to upgrade a requirement locally before I update requirements (and without wanting to do a full requirements update which wipes out any local changes to -e installed packages) - it's surprising if doing this also upgrades Django itself. (of course it's possible that other packages get updated but this is both less common and less unpleasant to deal with)

The other side of this - what benefit is there in including Django in install_requires which isn't better served by using the system check framework?

Apologies if I've misunderstood something.

**Comment by brianmay** [comment]
The only requirement django-guardian has is:

```
Django >= 1.7
```

pip not not be trying to upgrade Django unless it is too old for django-guardian to support.

**Comment by crccheck** [comment]
Frequently, pip will see that and "helpfully" upgrade Django versions for you when you already have a recent Django version.

**Comment by ad-m** [comment]
@brianmay , I disagree. pip trying to upgrade django everytime upgrade django-guardian.

```
$ pip install 'django==1.8'
Collecting django==1.8
  Using cached Django-1.8-py2.py3-none-any.whl
Installing collected packages: django
Successfully installed django-1.8
$ pip install django-guardian
Collecting django-guardian
Requirement already satisfied (use --upgrade to upgrade): six in ./test-django/lib/python2.7/site-packages (from django-guardian)
Requirement already satisfied (use --upgrade to upgrade): Django>=1.7 in ./test-django/lib/python2.7/site-packages (from django-guardian)
Installing collected packages: django-guardian
Successfully installed django-guardian-1.4.5
$ pip install django-guardian -U
Requirement already up-to-date: django-guardian in ./test-django/lib/python2.7/site-packages
Requirement already up-to-date: six in ./test-django/lib/python2.7/site-packages (from django-guardian)
Collecting Django>=1.7 (from django-guardian)
  Using cached Django-1.10.1-py2.py3-none-any.whl
Installing collected packages: Django
  Found existing installation: Django 1.8
    Uninstalling Django-1.8:
      Successfully uninstalled Django-1.8
Successfully installed Django-1.10.1
$ pip freeze
Django==1.10.1
django-guardian==1.4.5
pkg-resources==0.0.0
six==1.10.0
$ pip --version
pip 8.1.2 from /tmp/test-django/local/lib/python2.7/site-packages (python 2.7)
```

**Comment by brianmay** [comment]
Of course it will upgrade packages if you specify ``-U`` - that is the entire point of ``-U``.

Maybe what you want is ``pip install django-guardian==1.4.5`` if you only want to upgrade django-guardian.

**Comment by andybak** [comment]
> Of course it will upgrade packages if you specify -U - that is the entire point of -U

Yes one doesn't expect pip install django-guardian -U to upgrade Django.

Do a survey of other django apps - the ones that do this are in the distinct minority.

Can I reiterate my other point?

Even if you and I disagree on the disadvantages - there are no *advantages* that aren't much better solved by a combination of a line in the README and an check via the system check framework.

**Comment by brianmay** [comment]
It seems bizarre to me that you wouldn't want to list Django as a dependency. Will leave it to @ad-m to decide however if he wants to change it or not.
