### ISSUE TITLE
Incompatible setup_requires setting in setup.py

### ISSUE THREAD

**Issue by jcmcken** [django-guardian/django-guardian#425]
As it stands, the ``setup_requires`` setting in ``setup`` is largely incompatible with how ``pip`` handles dependency resolution when performing installations. See pypa/pip#1820, pypa/pip#769, pypa/pip#410. While there are some suggested workarounds and hacks to get it to work, they may or may not work depending on exactly how you're doing the installation.

From what I can tell, these setup dependencies are just used to write out the version file, and so it would seem to be a pretty simple alternative to just do that explicitly without any setup dependencies. What do you think?

**Comment by brianmay** [comment]
Using setup_requires is the recommended way of using setuptools-scm. Straight from their documentation: https://pypi.python.org/pypi/setuptools_scm/1.0.0

setuptools-scm does more then just write the version file, it also determines the correct version to use based on information from git and other sources such as PKG_INFO. It really is required.

Why not just make sure setuptools-scm is installed before calling ``setup.py``?

**Comment by brianmay** [comment]
No response; closing. Can reopen if required.
