### ISSUE TITLE
prefetch_perms caching incorrect for object without perms

### ISSUE THREAD

**Issue by pgeez** [django-guardian/django-guardian#426]
`prefetch_perms` will only cache objects in the ObjectPermissionChecker's `_obj_perms_cache` if a Permission exists for that object.

see: https://github.com/django-guardian/django-guardian/blob/devel/guardian/core.py#L252-L261

Therefore, if I call `prefetch_perms` on an object `foo` for which I *do not* have any permissions, successive calls to `has_perm("some_perm", foo)` will result in additional DB queries.

**Comment by brianmay** [comment]
Fixed in #427.
