### ISSUE TITLE
How to represent a permission that is not tied to an object like create / new CRUD actions?

### ISSUE THREAD

**Issue by cirosantilli** [django-guardian/django-guardian#428]
E.g., for a "create" CRUD action, you don't have the object yet.

Can Guardian represent this? How? Can I write something like:

    request.user.has_perm('new_article')

without the obejct?

I think the Django permissions can deal with this... but I'd rather have a Guardian method for uniformity.

**Comment by ad-m** [comment]
As in clean Django without django-guardian. Clean Django have API have per-object permission which implement django-guardian.
'''
request.user.has_perm('new_article')
'''
or
'''
request.user.has_perm('new_article', obj)
'''
See https://docs.djangoproject.com/en/1.9/ref/contrib/auth/#django.contrib.auth.models.User.has_perm

**Comment by cirosantilli** [comment]
Ah, doh, the APIs are the same already.
