### ISSUE TITLE
Need to override UserManage class 

### ISSUE THREAD

**Issue by pk026** [django-guardian/django-guardian#441]
I need to make user selection as drop down from User present in database in integration with django admin.

**Comment by pk026** [comment]
added following lines in model.py and its working. 
GroupManage.base_fields['group'] = forms.ModelChoiceField(queryset=Group.objects.all().order_by('name'))
UserManage.base_fields['user'] = forms.ModelChoiceField(queryset=User.objects.all().order_by('username'))

**Comment by ad-m** [comment]
If you like overwrite django-guardian forms you can easily use ``GuardedModelAdminMixin.get_obj_perms_user_select_form`` and ``GuardedModelAdminMixin.get_obj_perms_group_select_form`` .

For example:
```python
from django.contrib import admin
from guardian.admin import UserManage, GroupManage
from .models import MyModel

class CustomUserManage(UserManage):
    pass
class CustomGroupManage(GroupManage):
    pass

@admin.register(MyModel)
class MyAdmin(GuardedModelAdminMixin,admin.ModelAdmin):
    def get_obj_perms_user_select_form(self, request):
        """
        Returns form class for selecting a user for permissions management. 
        """
        return CustomUserManage

    def get_obj_perms_group_select_form(self, request):
        """
        Returns form class for selecting a group for permissions management.
        """
        return CustomGroupManage
