### ISSUE TITLE
Django 1.10 compatibility for GuardedModelAdminMixin

### ISSUE THREAD

**Issue by tdruez** [django-guardian/django-guardian#442]
From https://docs.djangoproject.com/en/1.10/releases/1.10/#features-removed-in-1-10

> The dictionary and context_instance parameters for the following functions are removed:
django.shortcuts.render()
django.shortcuts.render_to_response()
django.template.loader.render_to_string()

See also related https://github.com/django-guardian/django-guardian/issues/370

`render_to_response` in
- 1.10: https://github.com/django/django/blob/stable/1.10.x/django/shortcuts.py#L16
- 1.9: https://github.com/django/django/blob/stable/1.9.x/django/shortcuts.py#L27

The following lines needs to be fixed in django-guardian:
- https://github.com/django-guardian/django-guardian/blob/devel/guardian/admin.py#L217
- https://github.com/django-guardian/django-guardian/blob/devel/guardian/admin.py#L268
- https://github.com/django-guardian/django-guardian/blob/devel/guardian/admin.py#L341

The `RequestContext(request)` vars are provided as the `content_type` argument of the new `render_to_response` function. This breaks the rendering of the view.

**Comment by brianmay** [comment]
Assuming this is closed now that I merged #443. If not, please let me know.
