### ISSUE TITLE
Make the fact that "django-guardian" is actively maintained more clear

### ISSUE THREAD

**Issue by cdman** [django-guardian/django-guardian#446]
Hello,

I was looking around for a row-level (object level) permission framework for Django and found django guardian through google searches and this presentations from PyCon 2016: https://www.youtube.com/watch?v=C0wuTkS93B0

However at first I was under the impression that it isn't maintained for any longer due to:

- the [documentation](http://django-guardian.readthedocs.io/en/latest/) saying "Copyright 2010-2013"
- the [overview page](http://django-guardian.readthedocs.io/en/latest/overview.html) talking about Django 1.2

Fortunately I saw on DjangoPackages.org that a lot of people use it and took a second look and realized that it is in fact actively maintained and a version was released just earlier this month. A couple of small documentation changes could such misunderstandings in the future.

PS. In the end I ended up going with the "rules" package since my use case is better suited to that (I don't need to create arbitrary links "this-user-can-access-that-object" but rather have clear rules like "every user can access the objects they own").

**Comment by brianmay** [comment]
I don't have time to give this package the attention it deserves. I just approve pull requests and make an occasional release as required.

I am not sure if I should be making changes to the copyright statement - I am not the copyright holder, and the copyright holder has not made any recent contributions. Maybe I should add my name to the copyright holders list? Although a lot of the changes being merged are not mine.

Pull requests to fix the overview page appreciated. I am not sure if that statement holds true or not for latest version's of Django, and I haven't had the time to check this.

**Comment by lukaszb** [comment]
@cdman thanks for sharing thoughts, I'm pretty sure you are not alone.

I'll try to address those.

**Comment by ad-m** [comment]
I think in first section of README.rst is good to mention a list of supported Django version.

**Comment by ad-m** [comment]
I think pypi package description is important too. https://pypi.python.org/pypi/django-guardian

**Comment by ad-m** [comment]
I added list of requirements to list supported django versions and even mention django 1.10 in #452 .
