### ISSUE TITLE
import PermissionListMixin Fails on new installs

### ISSUE THREAD

**Issue by aswincsekar** [django-guardian/django-guardian#453]
way to reproduce the error

`virtualenv env`
`source env/bin/activate`
`pip install django`
`pip install django-guardian`
`django-admin.py startproject testing .`

Add 'guardian' to INSTALLED_APPS in testing/settings.py

`python manage.py shell`

`import guardian`

The above code works

`from guardian.mixins import PermissionRequiredMixin, PermissionListMixin`

The above code returns error `ImportError: cannot import name PermissionListMixin`

**Comment by ad-m** [comment]
Yes. Added in #434, reverted in fa0a49acb17c50fc696904a7b8a5dd2e338fbd80 (mistake) and added again in #449. In the next release will be fixed, and the appropriate changes were made.

**Comment by ad-m** [comment]
@brianmay , do you can make a new release with fix above?

**Comment by brianmay** [comment]
Adam Dobrawy <notifications@github.com> writes:

> @brianmay , do you can make a new release with fix above? 

First, can you please add a new entry with the changes in the CHANGES
file?

Thanks
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by ad-m** [comment]
@brianmay , i do it today.

**Comment by BenDevelopment** [comment]
How about this new release ? :)

**Comment by ad-m** [comment]
@BenDevelopment , blocked by #457. Review are welcome.

**Comment by ad-m** [comment]
In the current django-guardian everything it is available and working correctly.
