### ISSUE TITLE
user.has_perm('add_myobject') allways returns false if permission only in group

### ISSUE THREAD

**Issue by BenDevelopment** [django-guardian/django-guardian#455]
I have a user, my user has a group, this group has 'add_myobject' permission.
Why user.has_perm('add_myobject') returns allways false ? (I've double checked in my database if all the relations are correctly set and all is ok: the group have the permission and the user have the group in his groups list)
Is there a workarround or another way to check user permissions with group "inheritance" ?
I'm not using the last release version, I'm using the la version of this repository.

**Comment by ad-m** [comment]
@BenDevelopment , do you know how to write test case? Do you remember about permission cache (see https://docs.djangoproject.com/en/1.10/topics/auth/default/#permission-caching )?

I wrote test case to proof preserve user permissions when added to a group with privileges. Here is it: https://github.com/django-guardian/django-guardian/commit/b4c8b64133620da2571e48763be5cd7d71802ccb
You can run the test case by download git checkout and eg.: ```pip install tox;  tox -e example-py27-django19```.

**Comment by BenDevelopment** [comment]
Thank you for you answer. The tests you wrote works. The problem comes from the cache (I had not read that part of the doc!).

**Comment by ad-m** [comment]
I am not sure about archiving deleted branch by GitHub, so I copy here above non-merged commit for archiving purpose.

```diff
diff --git a/example_project/articles/tests.py b/example_project/articles/tests.py
index 35993a6..21b2efc 100644
--- a/example_project/articles/tests.py
+++ b/example_project/articles/tests.py
@@ -5,6 +5,7 @@
 from articles.models import Article
 from articles.views import (ArticleCreateView, ArticleDeleteView, ArticleDetailView,
                             ArticleListView, ArticleUpdateView)
+from django.contrib.auth.models import Group
 
 
 class ViewTestCase(TestCase):
@@ -96,3 +97,21 @@ def test_delete_denied(self):
         view = ArticleDeleteView.as_view()
         response = view(request, slug='foo-slug')
         self.assertEqual(response.status_code, 302)
+
+    def test_group_and_user_indepenent(self):
+        group = Group.objects.create(name="example")
+        assign_perm('articles.view_article', group)
+        self.assertFalse(self.user.has_perm('articles.view_article'))
+
+    def test_group_provide_permission(self):
+        group = Group.objects.create(name="example")
+        assign_perm('articles.view_article', group)
+        self.user.groups.add(group)
+        self.assertTrue(self.user.has_perm('articles.view_article'))
+
+    def test_preserve_user_permissions_when_added_to_a_group_with_privileges(self):
+        group = Group.objects.create(name="example")
+        assign_perm('articles.view_article', group)
+        self.user.groups.add(group)
+        assign_perm('articles.view_article', self.user)
+        self.assertTrue(self.user.has_perm('articles.view_article'))
```
