### ISSUE TITLE
get_users_with_perms - with_group_users = False and attach_perms = True returns group permissions.

### ISSUE THREAD

**Issue by hackoder** [django-guardian/django-guardian#46]
Calling get_users_with_perms with with_group_users = False and attach_perms = True still returns those permissions that the user has through a group.

Test case:
- Create a user and grant 'read' permissions to an object
- Assign user to group.
- Assign group 'write' permissions to object.

get_users_with_perms(with_group_users = False, attach_perms = True) returns both 'read' and 'write'.

**Comment by mitar** [comment]
I think this was fixed with #403.

**Comment by kewama** [comment]
It is fixed in version 1.4.2.
