### ISSUE TITLE
Link to docs on PyPI is outdated

### ISSUE THREAD

**Issue by michael-k** [django-guardian/django-guardian#461]
It points to http://pythonhosted.org/django-guardian/ twice, which has documentation for django-guardian 1.1.0 instead of https://django-guardian.readthedocs.io/en/stable/.

**Comment by ad-m** [comment]
@brianmay , i am unable to fix that. I don't have permission to PyPI.

**Comment by brianmay** [comment]
The long description was not being generated properly in ``PKG-INFO``. I hope this was not my code... Hopefully on the next release PyPI should get the correct meta information automatically.

**Comment by brianmay** [comment]
The long description fixed in f0b9743214711b04e5bf14fbbcd38f69ea7d7a12

**Comment by ad-m** [comment]
I received permission to python packages on pypi. I removed outdated docs on pythonhosted.org, so no more misleading and outdated docs.
