### ISSUE TITLE
Invalid tutorian for configuration

### ISSUE THREAD

**Issue by Imperat** [django-guardian/django-guardian#467]
Hello, guys! I follow this instruction (http://django-guardian.readthedocs.io/en/stable/configuration.html) for implement django-guardian in my project.  
1. I add guardian in my `INSTALLED_APPS`.
2. I add this lines: 
```
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend',
)
```
3. And anonimus user configuration: `ANONYMOUS_USER_ID = None`
4. In admin file I was importing with this line:
` from guardian.admin import GuardedModelAdmin`
5. And I was make this inheritance:
`class LeagueAdmin(GuardedModelAdmin):`
6. I run `python manage.py migrate`
7. I run server and I'm going to admin panel in list of Leagues. I see the button `objects permissions`. It's linked to http://127.0.0.1:8080/admin/teamlogic/tournament/2/change/permissions/. This is wrong link. Good link is: http://127.0.0.1:8080/admin/teamlogic/tournament/2/permissions/. I think this is a bug of django-guardian package. I check it in other project and I register a similar bug.

**Comment by Imperat** [comment]
Oh, sorry. I start debug this problem and I see that this problem was fixed at december 2015 year.

**Comment by Imperat** [comment]
Also I will be very nice if you can help me with other question with django-gurdian :)

**Comment by ad-m** [comment]
@Imperat , what other questions do you have?

**Comment by ad-m** [comment]
Is there any open issues still?

**Comment by Imperat** [comment]
@ad-m I open other issue: https://github.com/django-guardian/django-guardian/issues/469
