### ISSUE TITLE
Bug in ObjectPermissionChecker class

### ISSUE THREAD

**Issue by Imperat** [django-guardian/django-guardian#469]
For show this bug I purpose to run the following commands:
```
>>>from guardian.core import ObjectPermissionChecker
>>>from django.contrib.auth.models import Group, User
>>>from teamlogic.models import Stadium
>>>user = User.objects.create(username=...)
>>>group = Group.objects.create(name=...)
>>>checker = ObjectPermisionChecker(user)
>>>stadiums = Stadium.objects.all()
>>>checker.has_perm('change_stadium, stadiums[0])
False
>>>assign_perm('teamlogic.change_stadium', user)
>>>checker = ObjectPermisionChecker(user)
>>>checker.has_perm('change_stadium', stadiums[0])
False # Expected True
```

In my snippet Stadium is my custome django model)

**Comment by gabn88** [comment]
You have assigned the 'model' change_stadium permission to the user, not the object permission, therefore it is not working like you think. You would have to omit stadiums[0] in your last call to make it check for the 'model' permission, or give explicit permissions to that object.

I think this can be closed.

**Comment by ad-m** [comment]
@gabn8, you are right. Django-guardian don't use global permission in default. There is no support in ```ObjectPermisionChecker``` to query about global permission. For example ```get_objects_for_user``` support ```accept_global_perms``` (default disabled) then takes global permissions into account.

**Comment by Imperat** [comment]
Thanks for your reply, guys! :)
