### ISSUE TITLE
How to import PermissionsMixin

### ISSUE THREAD

**Issue by mowujilun** [django-guardian/django-guardian#471]
I followed the document to customise django user class

"To fix this, it is recommended to add the setting GUARDIAN_MONKEY_PATCH = False in your settings.py and add the GuardianUserMixin to your custom user model."

my customised user class extent AbstractBaseUser and PermissionsMixin
class MyUser(AbstractBaseUser, PermissionsMixin):
        pass.....

but i cant find the namespace of "PermissionsMixin", how to import this class in the model.py

**Comment by ad-m** [comment]
Propably do you want use:
```
from guardian.mixins import GuardianUserMixin
```

I don't know what mention ``PermissionMixin``. It's looks official and up-to-date django-guardian docs doesn't mention that any way (see https://django-guardian.readthedocs.io/en/stable/search.html?q=PermissionsMixin&check_keywords=yes&area=default ).

Greetings,
