### ISSUE TITLE
`guardian.mixins.PermissionRequiredMixin` fails with `django.views.generic.View`:

### ISSUE THREAD

**Issue by NAThompson** [django-guardian/django-guardian#476]
When using `guardian.mixins.PermissionRequiredMixin`, the permission check fails when the view inherits from `View`, `ListView`, and `TemplateView`, but not when it inherits from `UpdateView`, `DeleteView`, or `CreateView`.

Example:

```python
from guardian.mixins import PermissionRequiredMixin
from django.views.generic import View
from django.views.generic import CreateView

# Will fail:
class FooView1(PermissionRequiredMixin, View):
    template_name = 'foo.html'
    model = Foo
    permission_required = 'app.delete_foo'
    return_403 = True

# Will succeed:
class FooView2(PermissionRequiredMixin, CreateView):
    template_name = 'foo.html'
    model = Foo
    permission_required = 'app.delete_foo'
    return_403 = True
```

Environment: Django 1.10.3, Python 3.5.1, using a custom user model.

**Comment by NAThompson** [comment]
My bad; this is explained by the docstring of the PermissionRequiredMixin class.

**Comment by ad-m** [comment]
Use ``guardian.mixins.PermissionListMixin`` for ``django.views.generic.ListView``.
