### ISSUE TITLE
Troubles querying the object permissions in view

### ISSUE THREAD

**Issue by hetsch** [django-guardian/django-guardian#482]
I'm currently having troubles to understand how object level permissions can be queried inside a django view instance. 

What I want to achieve is that `UserA` should be able to access his own user object (model instance), but is not allowed to access the user object instances of other users `UserB, UserC ...`. Therefore, I've assigned permissions via `assign_perm('view_dashboard', user, user)`. 

As far as I understood this, only `UserA` is allowed to view his own user model instance. What I was expecting is that if I query the current access permissions via `self.request.user.has_perm('view_dashboard', obj)` and `obj` is not the user model instance of the currently logged-in user, it would return `False` (not allowed), because only the currently logged-in user is permitted to access his/her own user object instance. 

But `self.request.user.has_perm('view_dashboard', obj)` returns `True` for every permission check on `obj`. Somehow it seems like there is something mixed with global permissions.

My current code is:

settings.py

    AUTHENTICATION_BACKENDS = (
        'django.contrib.auth.backends.ModelBackend',
        'allauth.account.auth_backends.AuthenticationBackend',
        'guardian.backends.ObjectPermissionBackend',
    )
    ANONYMOUS_USER_NAME = 'AnonymousUser'

users.models.py

    from django.contrib.auth.models import AbstractUser

    class User(AbstractUser):

        class Meta:
            # http://stackoverflow.com/a/28467698/1230358
            # default_permissions = ()
            permissions = (
                ('view_dashboard', _('Can view user dashboard')),
            )

users.apps.py

    from django.apps import AppConfig
    from django.db.models.signals import post_save
    from django.conf import settings

    class UsersConfig(AppConfig):
        name = 'core.users'
        verbose_name = "Users"

        def ready(self):
            from core.users.models import User
            post_save.connect(setup_user_permissions, sender=User)

    def setup_user_permissions(sender, **kwargs):
        from guardian.shortcuts import assign_perm

        user, created = kwargs["instance"], kwargs["created"]
        if created and user.username != settings.ANONYMOUS_USER_NAME:
            assign_perm('view_dashboard', user, user)

users.views.py

    class UserDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):

        model = User

        raise_exception = True

        def test_func(self):
            # get the user object model
            obj = self.get_object()

            # print(self.request.user.has_perm('view_dashboard', obj))
            # print(get_perms(self.request.user, obj))

            # Both return True also in the case if the currently logged in user 
            # (self.request.user) wants to view the dashboard of another user (obj).
            # This should not be the case because only the owner should have access
            # to the dashboard. Assigned via assign_perm('view_dashboard', user, user)

            # Returns True if UserA == obj of UserA (as expected)
            # Returns also True if UserA == obj of UserB (not expected)

            # return self.request.user.has_perm('view_dashboard', obj)
            return 'view_dashboard' in get_perms(self.request.user, obj)

The same happens if I use the `PermissionRequiredMixin` of guardian.

    class UserDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):

        model = User

        permission_required = 'users.view_dashboard'
        # accept_global_perms = True
        # accept_global_perms = False

        # raise exception instead of endlessly redirecting to login url
        raise_exception = True

**Comment by ad-m** [comment]
I don't see any bug in examples. See https://github.com/django-guardian/django-guardian/blob/devel/example_project/articles/views.py .

Do you can provide output of SQL queries:
```python
import logging
l = logging.getLogger('django.db.backends')
l.setLevel(logging.DEBUG)
l.addHandler(logging.StreamHandler())
```

**Comment by hetsch** [comment]
Indeed strange ... Assume that I'm logged in as UserA and accessing the profile of UserB

    [22/Dec/2016 12:58:48] "GET /users/UserB/ HTTP/1.1" 200 13141
    v(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'k8jfud96xuerenxbh7km6fdq6gcjz698' AND "django_session"."expire_date" > '2016-12-22 13:02:42.413693'); args=('k8jfud96xuerenxbh7km6fdq6gcjz698', '2016-12-22 13:02:42.413693')
    (0.000) SELECT "users_user"."password", "users_user"."last_login", "users_user"."is_superuser", "users_user"."username", "users_user"."first_name", "users_user"."last_name", "users_user"."email", "users_user"."is_staff", "users_user"."is_active", "users_user"."date_joined", "users_user"."id", "users_user"."name" FROM "users_user" WHERE "users_user"."id" = 'fe8337036826412eb55bd4364e4a5210'; args=('fe8337036826412eb55bd4364e4a5210',)
    (0.000) SELECT "users_user"."password", "users_user"."last_login", "users_user"."is_superuser", "users_user"."username", "users_user"."first_name", "users_user"."last_name", "users_user"."email", "users_user"."is_staff", "users_user"."is_active", "users_user"."date_joined", "users_user"."id", "users_user"."name" FROM "users_user" WHERE "users_user"."username" = 'UserA'; args=('UserA',)
    (0.000) SELECT "users_user"."password", "users_user"."last_login", "users_user"."is_superuser", "users_user"."username", "users_user"."first_name", "users_user"."last_name", "users_user"."email", "users_user"."is_staff", "users_user"."is_active", "users_user"."date_joined", "users_user"."id", "users_user"."name" FROM "users_user" WHERE "users_user"."username" = 'UserA'; args=('UserA',)


And accessing my own profile

    22/Dec/2016 13:02:42] "GET /users/UserA/ HTTP/1.1" 200 13298
    (0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'k8jfud96xuerenxbh7km6fdq6gcjz698' AND "django_session"."expire_date" > '2016-12-22 13:03:06.866629'); args=('k8jfud96xuerenxbh7km6fdq6gcjz698', '2016-12-22 13:03:06.866629')
    (0.000) SELECT "users_user"."password", "users_user"."last_login", "users_user"."is_superuser", "users_user"."username", "users_user"."first_name", "users_user"."last_name", "users_user"."email", "users_user"."is_staff", "users_user"."is_active", "users_user"."date_joined", "users_user"."id", "users_user"."name" FROM "users_user" WHERE "users_user"."id" = 'fe8337036826412eb55bd4364e4a5210'; args=('fe8337036826412eb55bd4364e4a5210',)
    (0.000) SELECT "users_user"."password", "users_user"."last_login", "users_user"."is_superuser", "users_user"."username", "users_user"."first_name", "users_user"."last_name", "users_user"."email", "users_user"."is_staff", "users_user"."is_active", "users_user"."date_joined", "users_user"."id", "users_user"."name" FROM "users_user" WHERE "users_user"."username" = 'UserB'; args=('UserB',)
    (0.000) SELECT "users_user"."password", "users_user"."last_login", "users_user"."is_superuser", "users_user"."username", "users_user"."first_name", "users_user"."last_name", "users_user"."email", "users_user"."is_staff", "users_user"."is_active", "users_user"."date_joined", "users_user"."id", "users_user"."name" FROM "users_user" WHERE "users_user"."username" = 'UserB'; args=('UserB',)

I might be wrong, but I cannot see any statements that are triggered by guardian? Might this has to do with assigning permissions, if the user (user) and object instance (user) are the same? E.g.  `assign_perm('view_dashboard', user, user)`

**Comment by ad-m** [comment]
@hetsch , did you use superuser?

**Comment by hetsch** [comment]
@ad-m , yes indeed UserA is a superuser.

**Comment by hetsch** [comment]
Jesus, logged in with UserB it's forbidden to see UserA's dashboard! Thank you so much! That means superusers are always allowed to do stuff, regardless of the permissions set? I've missed that in the documentation. Sorry! Thank's again!

**Comment by hetsch** [comment]
I'll close that issue because @ad-m solved it.

**Comment by ad-m** [comment]
There is no permission check for superuser. Django-guardian assumes superuser has all right to everything all time.

There is some comments in docs about that in Check object permissions section:
> Please remember that superusers would always get full list of permissions for a given object.

It is consistent with [django core docs](https://docs.djangoproject.com/en/1.10/ref/contrib/auth/):
>  is_superuser: Boolean. Designates that this user has all permissions without explicitly assigning them.

**Comment by hetsch** [comment]
Ahhh ... Makes totally sense. As said, sorry for wasting you time but helped me immensely! My bad!
