### ISSUE TITLE
Broken django db dump

### ISSUE THREAD

**Issue by ZuSe** [django-guardian/django-guardian#485]
Hi folks,

i am using django dump command to snapshot my db one note and  load the data into a newly created on another node. Since I installed django-guardian it seems not possible anymore. It breaks on:
 
Traceback (most recent call last):
  File "/home/django/my_project/venv/lib/python3.5/site-packages/django/db/models/fields/related.py", line 600, in __get__
    rel_obj = getattr(instance, self.cache_name)
AttributeError: 'Account' object has no attribute '_othermodel_cache'

Do you have idea what could cause him expecting the _cache attribute?

Best,
Patrick

**Comment by ad-m** [comment]
I am currently a little busy. I try to look at it after 5 February, ok?

**Comment by brianmay** [comment]
What version of Django?

**Comment by ZuSe** [comment]
@brianmay  1.8.9 with guardian 1.4.2

@ad-m thanks

**Comment by ZuSe** [comment]
@ad-m Have you found some time to look on it?

**Comment by ad-m** [comment]
@ZuSe , the stack trace is not full and I am unable to reproduce your issue.

I prepared some tests case which don't show any errors.

```python
class DumpDataTestCase(TestCase):

    def setUp(self):
        self.user = get_user_model().objects.create_user(
            'joe', 'joe@example.com', 'joe')
        self.post = Post.objects.create(title='foo-post-title')

    def test_minimal_dumpdata(self):
        self.user.add_obj_perm('change_post', self.post)
        args = []
        opts = {}
        call_command('dumpdata', *args, **opts)
```

Do you can provide some details?

**Comment by ZuSe** [comment]
Yeah, i will as soon as I have some free minutes.

What i found out that it happens when the model has post_save signals attached.
I now helped myself by preventing the execution of post_save by checking for raw input
