### ISSUE TITLE
assign_perm() on QuerySet has unpredicted behaviour

### ISSUE THREAD

**Issue by primoz-k** [django-guardian/django-guardian#490]
If I execute `assing_perm` on a QuerySet like this:

```python
assign_perm('view_person', user, persons_queryset)
```

After this line is executed, User, for who I'm setting permission, might not have  `view_person` permission to all of the objects in `persons_queryset`.

Does anybody have the same problem?

**Comment by ad-m** [comment]
@primoz-k , I am not sure what do you mean. Do you can prepare test case to expose the problem?

**Comment by primoz-k** [comment]
@ad-m Sorry, the problem was somewhere else in the code where this line was executed and this was just a result. `assing_perm()` works as it should, closing the issue.
