### ISSUE TITLE
django-guardian not reporting correctly with has_perm in shell

### ISSUE THREAD

**Issue by typistX** [django-guardian/django-guardian#503]
So I'm using django-guardian with a custom User model, but it's acting up. I did implement all changes as advised in the docs.

Assume the following shell session:

    >>> our_user = GeneralUser.objects.get(id=25)
    >>> our_biz = Business.objects.get(id=5)
    >>> assign_perm('delete_business', our_user, our_biz)
    <UserObjectPermission: UserObjectPermission object>
    >>> our_user.has_perm('delete_business', our_biz)
    False

This has led me me to believe that maybe trying to edit one of django's built-in permissions (`add|change|delete`) isn't possible through guardian, so I tried to the permission label to `del_business`, but got the *same result as above*.

But upon inspecting the table `guardian_userobjectpermission` I can see that the above session, and in fact all of my attempts were successful:

[![enter image description here][1]][1]

So why does `.has_perm` always report `False` when I check?

The only case where `has_perm` returns True is when both objects (User & Business) are **created** within the shell session. Otherwise it always returns `False`, even though its SQL-table clearly says it should be `True`.

  [1]: https://i.stack.imgur.com/Yjvyg.png

**Comment by ad-m** [comment]
@typistX , do you can prepare example using [example_project](https://github.com/django-guardian/django-guardian/tree/devel/example_project) to make issue reproducible?

**Comment by typistX** [comment]
@ad-m Thanks for replying.

Well, Doing this with example_project I think would be the same as I did it. I already went through this example, project (without actually using shell), and all seemed fine. But it doesn't use a custom user model, and actually does not refer to user anywhere.

I will try anyway.

**Comment by typistX** [comment]
I did this with the example_project and `guardian` shell session behaved as expected.

I tried implementing my own user instead, so I wiped the directory, re-downloaded, and before migrating replaced the model with my own `AbstractUser` sublass, going to the admin and setting it as the default model, and then replacing references.

`makemigrations` worked but `migrate` throws the following (attached below). It seems something in manage.py is preventing the model to be resolved, which is very weird.



> File "manage.py", line 17, in <module>
>     execute_from_command_line(sys.argv)
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
>     utility.execute()
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/core/management/base.py", line 305, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/core/management/base.py", line 356, in execute
>     output = self.handle(*args, **options)
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 202, in handle
>     targets, plan, fake=fake, fake_initial=fake_initial
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/db/migrations/executor.py", line 97, in migrate
>     state = self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/db/migrations/executor.py", line 132, in _migrate_all_forwards
>     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/db/migrations/executor.py", line 237, in apply_migration
>     state = migration.apply(state, schema_editor)
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
>     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
>     schema_editor.create_model(model)
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 246, in create_model
>     definition, extra_params = self.column_sql(model, field)
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 136, in column_sql
>     db_params = field.db_parameters(connection=self.connection)
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/db/models/fields/related.py", line 940, in db_parameters
>     return {"type": self.db_type(connection), "check": self.db_check(connection)}
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/db/models/fields/related.py", line 937, in db_type
>     return self.target_field.rel_db_type(connection=connection)
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/db/models/fields/related.py", line 855, in target_field
>     return self.foreign_related_fields[0]
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/db/models/fields/related.py", line 595, in foreign_related_fields
>     return tuple(rhs_field for lhs_field, rhs_field in self.related_fields if rhs_field)
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/db/models/fields/related.py", line 582, in related_fields
>     self._related_fields = self.resolve_related_fields()
>   File "/Users/censored/.virtualenvs/example_guardian_temp/lib/python3.5/site-packages/django/db/models/fields/related.py", line 567, in resolve_related_fields
>     raise ValueError('Related model %r cannot be resolved' % self.remote_field.model)
> ValueError: Related model 'core.GeneralUser' cannot be resolved

**Comment by typistX** [comment]
**Update:**

I wiped the database on the **example_project** once again, and now guardian is behaving fine even with my GeneralUser model. Must be something that I'm misconfiguring in my project. But what could it be? Specifically affecting the shell?

**Comment by typistX** [comment]
I've found the culprit, just hoping someone can help:

Django-guardian will create and report permissions for users registered through the admin panel. However, it **will** create **but not report** permissions for users registered through my app.forms. Here's my form:

```
class GeneralUserForm(UserCreationForm):
    business_name = forms.CharField(required=True)

    class Meta:
        model = GeneralUser
        fields = ['username', 'email', 'password1',
                  'password2', 'business_name']

    def save(self, commit=True):
        user = super(GeneralUserForm, self).save(commit=True)
        business = Business(name=user.business_name, owner=user)

        user.save()
        business.save()
        assign_perm('delete_business', user, business)

        return user
```

Why doesn't `django-guardian` report `True` for permissions that are there, that I don't know. 

Any ideas?

**Comment by typistX** [comment]
Since this thread's title is no longer correct, and it includes a lot of incorrect information, I've opened a new one which describers the problem better.
