### ISSUE TITLE
Groups by objects

### ISSUE THREAD

**Issue by imaia** [django-guardian/django-guardian#518]
How could I consult all groups by a queryset of objects? Like: list me these objects and fetch them with groups that have a certain right over them.

**Comment by ad-m** [comment]
Hello @imaia ,

If you use [direct foreign key ](https://django-guardian.readthedocs.io/en/stable/userguide/performance.html#direct-foreign-keys) you can use ``casegroupobjectpermission_set`` attribute and [Prefetch() objects](https://docs.djangoproject.com/en/1.7/ref/models/queries/#prefetch-objects). See [prefetch_related()](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#prefetch-related) examples.

So it will be  something like:
```
Case.objects.prefetch_related(Prefetch('groups_with_perm', queryset=CaseGroupObjectPermission.objects.filter(permission__name='x').all())))
```
