### ISSUE TITLE
Proposal: action for multiple permission assign

### ISSUE THREAD

**Issue by mmornati** [django-guardian/django-guardian#52]
With many objects could be a very long work to assign object permissions to any object. A used thing to have could be an Action (in the combo box, like delete one) that allow you to select multiple objects and then set permissions for all of them.

Action I suppose is the fastest way to do it (and maybe the cleanest way too), but any other method to multiple assign perms to object is welcome.

Thanks 
Marco

**Comment by brianmay** [comment]
This should be fixed now #436 was merged.
