### ISSUE TITLE
django-guardian don't support multiple databases?

### ISSUE THREAD

**Issue by suparek** [django-guardian/django-guardian#520]
I write it to my settings.py
`
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'hivetest': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hivetest',
        'USER': 'root',
        'PASSWORD': 'ladyroot',
        'HOST': 'localhost',
        'PORT': '3306',
    },
}

`

but when I change the object permission,it said to me 
`

Request Method: | POST
-- | --
http://127.0.0.1:8000/admin/test/testdata/7/permissions/user-manage/2/
1.11.3
OperationalError
no such table: testdata
/home/yangtz/anaconda3/envs/xinfang/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py in execute, line 328
/home/yangtz/anaconda3/envs/xinfang/bin/python
3.6.0

`

**Comment by ad-m** [comment]
Repositories do not use automated tests for multiple databases, so support for multiple databases is not guaranteed.
