### ISSUE TITLE
Permission for specific object in AdminPanel

### ISSUE THREAD

**Issue by Allan-Nava** [django-guardian/django-guardian#536]
Hi, is possibile have the same feature of this example:

```
>>> from django.contrib.auth.models import User, Group
>>> jack = User.objects.create_user('jack', 'jack@example.com', 'topsecretagentjack')
>>> admins = Group.objects.create(name='admins')
>>> jack.has_perm('change_group', admins)
False
>>> from guardian.models import UserObjectPermission
>>> UserObjectPermission.objects.assign_perm('change_group', jack, obj=admins)
<UserObjectPermission: admins | jack | change_group>
>>> jack.has_perm('change_group', admins)
True

```
Inside the Panel admin?

Thanks for support.
Best Regards, Allan

**Comment by ad-m** [comment]
There is build-in django admin integration. See guardian.admin.GuardedModelAdmin ( https://django-guardian.readthedocs.io/en/stable/api/guardian.admin.html#guardian.admin.GuardedModelAdmin ) & admin integration ( https://django-guardian.readthedocs.io/en/stable/userguide/admin-integration.html ).

**Comment by Allan-Nava** [comment]
@ad-m Thanks, I have this admin.py and models.py

`from django.contrib import admin

from bootcamp.groups_manager.models import Group, Member, GroupType, GroupEntity, GroupMember, GroupMemberRole
from guardian.admin import GuardedModelAdmin

# With object permissions support
class GroupAdmin(GuardedModelAdmin):
    pass

#admin.site.register(models.Group)
admin.site.register(Group, GroupAdmin)
admin.site.register(Member)
admin.site.register(GroupType)
admin.site.register(GroupEntity)
admin.site.register(GroupMember)
admin.site.register(GroupMemberRole)`

`
class GroupMixin(GroupRelationsMixin, MPTTModel):
    """This model represents the group. Each group could have a parent group (via the `parent`
    attribute).

    :Parameters:
      - `name`: (required)
      - `codename`: NON unique codename; if not set, it's autogenerated by slugifying the label
        (lower case)
      - `description`: text field
      - `comment`: text field
      - `full_name`: auto generated full name starting from tree root
      - `properties`: jsonfield properties
      - `group_members`: m2m to Member, through GroupMember model (related name: `groups`)
      - `group_type`: foreign key to GroupType (related name: `groups`)
      - `group_entities`: m2m to GroupEntity (related name: `groups`)
      - `django_group`: django auth related group
      - `django_auth_sync`: synchronize or not the group (if setting DJANGO_AUTH_SYNC is True)
        (default: True)
      - `level`: ``django-mptt`` level attribute
        (default: True)

    .. note::
     If you want to add a custom manager for a sublcass of Group, use django-mptt
     mptt.models.TreeManager.

    """
    name = models.CharField(max_length=255)
    codename = models.SlugField(blank=True, max_length=255)
    description = models.TextField(default='', blank=True)
    comment = models.TextField(default='', blank=True)
    parent = TreeForeignKey('self', null=True, blank=True,
                            related_name='sub_%(app_label)s_%(class)s_set')
    full_name = models.CharField(max_length=255, default='', blank=True)
    properties = JSONField(default={}, blank=True,
                            load_kwargs={'object_pairs_hook': OrderedDict})

    django_auth_sync = models.BooleanField(default=True, blank=True)
    
    #Custom permission
    no_picture = django_settings.MEDIA_URL +'/group_pictures/avatar-team.jpg'
    no_cover = django_settings.MEDIA_URL +'/group_covers/covers.jpg'
    url_back = 'group_covers/'
    url_photo = 'group_pictures/'
    #background_photo = models.ImageField(upload_to =url_back, default=no_cover, null=True, blank=True)
    #profile_photo = models.ImageField(upload_to=url_photo, default=no_picture, null=True, blank=True)
    background_photo = models.CharField(max_length=255, null=True, blank=True)
    profile_photo = models.CharField(max_length=255, null=True, blank=True)
    #type = models.TextField(default='', blank=True)

    class Meta:
        abstract = True
        ordering = ('name', )

    class MPTTMeta:
        level_attr = 'level'
        order_insertion_by = ['name', ]

    class GroupsManagerMeta(GroupRelationsMixin.GroupsManagerMeta):
        pass

    def __unicode__(self):
        return '%s' % self.name

    def __str__(self):
        return '%s' % self.name

    def save(self, *args, **kwargs):
        self.full_name = self._get_full_name()[:255]
        if not self.codename:
            self.codename = slugify(self.name, to_lower=True)
        super(GroupMixin, self).save(*args, **kwargs)

    def _get_full_name(self):
        if self.parent:
            return '%s - %s' % (self.parent._get_full_name(), self.name)
        return self.name

    @property
    def subgroups(self):
        message = 'The "subgroups" attribute will be removed in next version. ' + \
                  'Use "sub_groups_manager_group_set" instead.'
        warnings.warn(message, DeprecationWarning)
        return self.sub_groups_manager_group_set

    def get_members(self, subgroups=False):
        """Return group members.
        The result is a list of GroupsManagerMeta's attribute ``member_model`` instances.

        :Parameters:
          - `subgroups`: return also descendants members (default: `False`)
        """
        member_model = self.member_model
        group_member_model = self.group_member_model
        if group_member_model == GroupMember:
            members_relation = getattr(self, self.group_members_attribute)
            if member_model == Member:
                members = list(members_relation.all())
            else:
                # proxy model
                if member_model._meta.proxy:
                    members = list(member_model.objects.filter(
                        id__in=members_relation.values_list('id', flat=True)))
                # subclassed
                else:
                    members = list(member_model.objects.filter(
                        member_ptr__in=members_relation.all()))
        else:
            members = [gm.member for gm in group_member_model.objects.filter(group=self)]
        if subgroups:
            for subgroup in self.subgroups.all():
                members += subgroup.members
        members = list(set(members))
        return members

    @property
    def members(self):
        """Return group members. """
        return self.get_members(True)

    @property
    def users(self):
        """Return group django users. """
        users = []
        for member in self.members:
            if member.django_user:
                users.append(member.django_user)
        return users

    def get_entities(self, subgroups=False):
        """Return group entities.

        :Parameters:
          - `subgroups`: return also descendants entities (default: `False`)
        """
        entities = list(self.group_entities.all())
        if subgroups:
            for subgroup in self.subgroups.all():
                entities += subgroup.entities
            entities = list(set(entities))
        return entities

    @property
    def entities(self):
        """Return group entities."""
        return self.get_entities(True)

    def add_member(self, member, roles=None):
        """Add a member to the group.
        :Parameters:
          - `member`: member (required)
          - `roles`: list of roles. Each role could be a role id, a role label or codename,
            a role instance (optional, default: ``[]``)
        """
        print("add_member() method")
        if roles is None:
            roles = []
        if not self.id:
            raise exceptions_gm.GroupNotSavedError(
                "You must save the group before to create a relation with members")
        if not member.id:
            raise exceptions_gm.MemberNotSavedError(
                "You must save the member before to create a relation with groups")
        group_member_model = self.group_member_model
        group_member = group_member_model(member=member, group=self)
        group_member.save()
        if roles:
            for role in roles:
                if isinstance(role, GroupMemberRole):
                    group_member.roles.add(role)
                elif isinstance(role, int):
                    role_obj = GroupMemberRole.objects.get(id=role)
                    group_member.roles.add(role_obj)
                else:
                    try:
                        role_obj = GroupMemberRole.objects.get(models.Q(label=role) |
                                                               models.Q(codename=role))
                        group_member.roles.add(role_obj)
                    except Exception as e:
                        raise exceptions_gm.GetRoleError(e)
        return group_member

    def remove_member(self, member):
        """Remove a member from the group.

        :Parameters:
          - `member`: member (required)
        """
        group_member_model = self.group_member_model
        try:
            group_member = group_member_model.objects.get(member=member, group=self)
        except Exception as e:
            raise exceptions_gm.GetGroupMemberError(e)
        group_member.delete()

    def assign_object(self, obj, **kwargs):
        """Assign an object to the group.

        :Parameters:
          - `obj`: the object to assign (required)

        :Kwargs:
          - `custom_permissions`: a full or partial redefinition of PERMISSIONS setting.

        .. note::
         This method needs django-guardian.
        """
        return assign_object_to_group(self, obj, **kwargs)

    #Custom Method
    def get_picture(self):
        no_picture = django_settings.MEDIA_URL +'/group_pictures/avatar-team.jpg'
        try:
            filename = django_settings.MEDIA_ROOT + '/group_pictures/' +\
                self.user.username + '.jpg'
            picture_url = django_settings.MEDIA_URL + 'group_pictures/' +\
                self.user.username + '.jpg'
            if os.path.isfile(filename):  # pragma: no cover
                return picture_url
            else:  # pragma: no cover
                gravatar_url = 'http://www.gravatar.com/avatar/{0}?{1}'.format(
                    hashlib.md5(self.user.email.lower()).hexdigest(),
                    urllib.urlencode({'d': no_picture, 's': '256'})
                    )
                return gravatar_url

        except Exception:
            return no_picture
    
    #Retrieve users' cover
    def get_cover(self):
        no_cover = django_settings.MEDIA_URL +'group_covers/cover.jpg'
        try:
            filename = django_settings.MEDIA_ROOT + '/group_covers/' +\
                self.user.username + '.jpg'
            cover_url = django_settings.MEDIA_URL + 'group_covers/' +\
                self.user.username + '.jpg'
            if os.path.isfile(filename) and os.path.exists(filename):  # pragma: no cover
                if cover_url != None:
                    return cover_url
                else:
                    return no_cover
            else:
                no_cover
        except Exception:
            return no_cover

class Group(GroupMixin):

    group_type = models.ForeignKey(GroupType, null=True, blank=True, on_delete=models.SET_NULL,
                                   related_name='%(app_label)s_%(class)s_set')
    group_entities = models.ManyToManyField(GroupEntity, blank=True,
                                            related_name='%(app_label)s_%(class)s_set')

    django_group = models.ForeignKey(DjangoGroup, null=True, blank=True, on_delete=models.SET_NULL)
    group_members = models.ManyToManyField(Member, through='GroupMember',
                                           related_name='%(app_label)s_%(class)s_set')

    # this is just required for easy explanation
    class Meta(GroupMixin.Meta):
        abstract = False
        permissions = (
            ('can_add_member_custom', 'Can Add Member Custom'),
            ('can_remove_member_custom', 'Can Remove Member Custom'),
            ('can_edit_group_custom', 'Can Edit Group Custom'),
        )`

**Comment by ad-m** [comment]
There is username input field. This is a typical behavior for Django that autocomplete mechanisms are extra.In the default Django Admin also there is no autocomplete, and at most a list of choices. There can be many items in the user box, so the simple list of choices is ineffective. If you want a more interactive field you can customize it yourself. If you like change behavior of that then you have to overwrite theme https://github.com/django-guardian/django-guardian/blob/devel/guardian/templates/admin/guardian/model/obj_perms_manage.html#L69 .

**Comment by Allan-Nava** [comment]
@ad-m Yes i need a list of choices like this:

![screen shot 2017-11-28 at 17 12 53](https://user-images.githubusercontent.com/22498435/33330565-71bbe9ee-d45f-11e7-9166-779c7fabbb70.png)


How can I overwrite the template of **Object Permission**?

**Comment by ad-m** [comment]
@Allan-Nava , [RTFD](https://docs.djangoproject.com/en/1.11/howto/overriding-templates/).

**Comment by Allan-Nava** [comment]
@ad-m But is possible tu pass the list of choices in admin.py inside class to set the users objects ?

Like this:
```
    member = forms.ModelChoiceField(queryset=models.Member.objects.all(),
                                   widget=forms.HiddenInput(), )
``` 

This is my admin.py
```
from django.contrib import admin
from django.contrib.auth.models import User

from bootcamp.groups_manager.models import Group, Member, GroupType, GroupEntity, GroupMember, GroupMemberRole
from guardian.admin import GuardedModelAdmin

# With object permissions support
class GroupAdmin(GuardedModelAdmin):
    #fields = ('group_members', 'django_group')
    #raw_id_fields = ('group_members',)
    #search_fields = ('group_members', 'django_group')
    #list_display = ('get_members', )
    filter_horizontal = ('group_members',)

    pass
    
#admin.site.register(models.Group)
admin.site.register(Group, GroupAdmin)
admin.site.register(Member)
admin.site.register(GroupType)
admin.site.register(GroupEntity)
admin.site.register(GroupMember)
admin.site.register(GroupMemberRole)
```

**Comment by Allan-Nava** [comment]
have already the overriding templates.
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

INSTALLED_APPS = [
    ...,
    'blog',
    ...,
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        ...
    },
]

This is my structure:
![screen shot 2017-11-28 at 18 21 47](https://user-images.githubusercontent.com/22498435/33334088-08294008-d469-11e7-9c98-1b2e1f9e5584.png)

Have i need to create templates/admin/guardian/model/field.html ?

I don't understand very well, sorry.

**Comment by ad-m** [comment]
@Allan-Nava , if you like overwrite fields python code then you have overwrite form at all. You can do it easily by overwriting ```GuardianModelAdminMixin.get_obj_perms_user_select_for```. See at source code of [GuardianModelAdminMixin.get_obj_perms_user_select_for](https://github.com/django-guardian/django-guardian/blob/devel/guardian/admin.py#L292) and [UserManage](https://github.com/django-guardian/django-guardian/blob/devel/guardian/admin.py#L456).

Instructions on the operation of the basic mechanisms of Django beyond the scope of this project.

**Comment by Allan-Nava** [comment]
@ad-m, What is the easy way to implement this functionality overwrite fields or overwrite the form?

I just want this select choices:
![screen shot 2017-11-28 at 17 12 53](https://user-images.githubusercontent.com/22498435/33330565-71bbe9ee-d45f-11e7-9166-779c7fabbb70.png)

Very very thanks for support! 👍 
Allan

**Comment by ad-m** [comment]
@Allan-Nava , i'm afraid it may require both. It all depends on the particular solution you use for the dropdown list.

**Comment by Allan-Nava** [comment]
@ad-m , Ok, so i need to do:

1. Create groups_manager(myapp)/templates/admin/ the html custom for **object permission**
2. Override GuardianModelAdminMixin.get_obj_perms_user_select_for and UserManage.

Missing something else ?

Thanks for support

**Comment by ad-m** [comment]
@Allan-Nava ,  it all depends on the particular solution you use for the autocomplete list. Select solution for the autocomplete list and follow the guide of them. There is no build-in support & any recommended solution for the autocomplete list.

**Comment by Allan-Nava** [comment]
@ad-m , I want a choice field like the image i attached. I can't fix only in admin.py inside a class **GroupAdmin**?

This is my admin.py class
```
# With object permissions support
class GroupAdmin(GuardedModelAdmin):
    #fields = ('group_members', 'django_group')
    #raw_id_fields = ('group_members',)
    #search_fields = ('group_members', 'django_group')
    #list_display = ('get_members', )
    filter_horizontal = ('group_members',)

    pass
```

Really thanks

**Comment by ad-m** [comment]
@Allan-Nava , it mostly depends on the particular solution you use for the autocomplete list. 

To overwrite GuardianModelAdminMixin.get_obj_perms_user_select_form and UserManage you have to write something like:

```python
class CustomUserManage(UserManage):
    pass

class GroupAdmin(GuardedModelAdmin):
    #fields = ('group_members', 'django_group')
    #raw_id_fields = ('group_members',)
    #search_fields = ('group_members', 'django_group')
    #list_display = ('get_members', )
    filter_horizontal = ('group_members',)

    def get_obj_perms_user_select_form(self, *args, **kwargs):
        return CustomUserManage
```

**Comment by Allan-Nava** [comment]
@ad-m , Ok thank's
Like this, correct?
```
from django.contrib import admin
from django.contrib.auth.models import User

from bootcamp.groups_manager.models import Group, Member, GroupType, GroupEntity, GroupMember, GroupMemberRole
from guardian.admin import GuardedModelAdmin

#guardian compat
from guardian.compat import get_model_name, get_user_model, url, reverse

#CustomClass to manage the field
class CustomUserManage(UserManage):
    '''user = forms.CharField(label=_("User identification"),
                           max_length=200,
                           error_messages={'does_not_exist': _(
                               "This user does not exist")},
                           help_text=_(
                               'Enter a value compatible with User.USERNAME_FIELD')
                           )'''
    user = forms.ModelChoiceField(queryset=Member.objects.all(),
                                    widget=forms.HiddenInput(),
                                    error_messages={'does_not_exist': _("This user does not exist")},
                                    help_text=_('Enter a value compatible with User.USERNAME_FIELD')))

    def clean_user(self):
        """
        Returns ``User`` instance based on the given identification.
        """
        identification = self.cleaned_data['user']
        user_model = get_user_model()
        try:
            username_field = user_model.USERNAME_FIELD
        except AttributeError:
            username_field = 'username'
        try:
            user = user_model.objects.get(**{username_field: identification})
            return user
        except user_model.DoesNotExist:
            raise forms.ValidationError(
                self.fields['user'].error_messages['does_not_exist'])

    pass

# With object permissions support
class GroupAdmin(GuardedModelAdmin):
    #fields = ('group_members', 'django_group')
    #raw_id_fields = ('group_members',)
    #search_fields = ('group_members', 'django_group')
    #list_display = ('get_members', )
    filter_horizontal = ('group_members',)

    def get_obj_perms_user_select_form(self, *args, **kwargs):
        return CustomUserManage

    pass
    
#admin.site.register(models.Group)
admin.site.register(Group, GroupAdmin)
```

Thanks

**Comment by ad-m** [comment]
Django-guardian does not impose any restrictions on the structure of this form. It is important that [the cleaned_user ['user'] field contains user instances](https://github.com/django-guardian/django-guardian/blob/devel/guardian/admin.py#L185
) after it has been successfully filled. 

Details on how to build forms, how the clean method works, etc. are discussed in the Django documentation. Your code looks bad, because the clean method looks invalid. In addition, the definition of the field contains unnecessary items.

**Comment by Allan-Nava** [comment]
Ok, I copy the same code of the Django-Guardian but with different Fields

**Comment by ad-m** [comment]
@Allan-Nava , read the docs what data provides ModelChoiceField and what data provides CharField. Django docs name it's as "Normalizes to". [RTFD](https://docs.djangoproject.com/en/1.11/ref/forms/fields/).

**Comment by Allan-Nava** [comment]
@ad-m Ok, thanks.

**Normalizes to: A Unicode object.**
I copy this ModelChoiceField inside the form of groups_manager (myapp)

Really thanks!

**Comment by Allan-Nava** [comment]
Ok tomorrow I debug my bad code, thanks for support!

Inviato da iPhone

**Comment by Allan-Nava** [comment]
@ad-m I fixed the object permission! Really thanks for support!!
