### ISSUE TITLE
Coexist django-guardian with django-moderation?

### ISSUE THREAD

**Issue by Allan-Nava** [django-guardian/django-guardian#539]
Hi,

can coexist [django-guardian](https://github.com/django-guardian/django-guardian) and [django-moderation](https://github.com/dominno/django-moderation/) in admin panel?

I need to handle an user's feed and activity with other user who have  the privilege.

Thank's for support

**Comment by ad-m** [comment]
I do not know this library, nor do I know the cases of proper integration of django-guardian with django-moderation. This does not exclude cooperation. It's best to just check and in case of problems, we can try to solve them and provide - if necessary - the appropriate API.

**Comment by Allan-Nava** [comment]
Because I need to implement in admin interface the django guardian and django moderation

**Comment by ad-m** [comment]
There is ``guardian.admin.GuardedModelAdminMixin``.

**Comment by Allan-Nava** [comment]
I know @ad-m  but I need both feature.

**Comment by thclark** [comment]
It doesn't look like these libraries are that easily compatible. It'd be interesting to see something in the ecosystem like `django-guardian-moderation` but I think such a thing is way out of the scope of this library.
