### ISSUE TITLE
Integration with django-entity

### ISSUE THREAD

**Issue by thclark** [django-guardian/django-guardian#568]
I'm thinking about binding django-guardian to [django-entity](https://github.com/ambitioninc/django-entity).

This will support the use case of granting permissions to other things than simply users. For example, an entity might represent:
- a user (vanilla, achievable with just django-guardian) 
- an agent acting on behalf of a user
- a machine instance or container
- a third party webservice

It will also support more complex relationship management than just users in groups. For example, datafiles in a dataset might be deemed to be accessible by entities which have access rights over the dataset (or equal and opposite, an entity might be refused access to a dataset if it doesn't also have access to the datafiles in the set).

Before disappearing to create a separate package ('django-entity-guardian', probably) to bind these two, I wanted to check:
 - Would there be any appetite for a pull request straight into django-guardian for this (I assume not)?
 - Anyone out there need the same thing and interested in collaborating?

**Comment by ad-m** [comment]
I did not have these kinds of needs, so I'm not interested. 

I think that the core django-guardian should be kept simple, so I suggest creating a separate package.  We are open to providing the necessary API if no available yet like the one for [django-polymorphic](http://django-polymorphic.readthedocs.io/en/stable/third-party.html#django-guardian-support) - see #431 .

**Comment by thclark** [comment]
@ad-m thanks, that's really helpful. That same API might even be usable for this purpose; I'll look into it. Closing this issue down for now.
