### ISSUE TITLE
get_groups_with_perms returns more perms than it should

### ISSUE THREAD

**Issue by mirekys** [django-guardian/django-guardian#596]
### Expected behavior
According to docs, the ```get_groups_with_perms``` function: 

> Returns queryset of all Group objects with any object permissions for the given obj.

### Actual behavior
It returns not only the given obj permissions, but also all permissions of any unrelated object/Model (of different ```content_type_id```) that has the same PK as the given obj.

### How to reproduce
``` python
# models.py
from django.db.models import Model, IntegerField, TextField

class ModelA(Model):
    num = IntegerField()

class ModelB(Model):
    text = TextField()
```
``` python
# requirements.txt
django-guardian==1.4.9
```
``` python
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
Django 2.1.5
>>> from .models import ModelA, ModelB
>>> a = ModelA.objects.create(num=1)
>>> b = ModelB.objects.create(text='b')

>>> from django.contrib.auth.models import Group
>>> admins = Group.objects.create(name='admins')

>>> assign_perm('change_modela', admins, obj=a)
<GroupObjectPermission: GroupObjectPermission object (1)>
>>> assign_perm('delete_modelb', admins, obj=b)
<GroupObjectPermission: GroupObjectPermission object (2)>

>>> from guardian.shortcuts import get_groups_with_perms
>>> get_groups_with_perms(b, attach_perms=True)
{<Group: admins>: ['change_modela', 'delete_modelb']}
```

**Comment by mirekys** [comment]
Just found this [commit](https://github.com/django-guardian/django-guardian/commit/aa0d417618f2093eb170396b1773d12c6505ab1c#diff-00305e2706413da2ce53d91a9f9c3655) in devel branch, that should fix the issue

**Comment by mirekys** [comment]
Can confirm that it fixes the issue, please close this after that fix is released

**Comment by ad-m** [comment]
@mireksys, does this mean that the problem has been removed and the issues can be closed?

**Comment by mirekys** [comment]
Yes, definitely :+1: I can see the fix already applied in the current master.
