### ISSUE TITLE
Version 1.5.0 release roadmap

### ISSUE THREAD

**Issue by ceelian** [django-guardian/django-guardian#600]
Are there any plans when django-guardian version 1.5.0 with python 3.7 and django 2.2 support will be released?

**Comment by ad-m** [comment]
The project has a limited number of maintaners. To release a new version of package is required to:

1. analyze the history of commits,
2. write changelog for users,
3. analyze what version it should be next according to semver,
4. bump  the version,
5. make & publish packages
There is no pending features to implement. Can you take actions in area 1-4? I have the permission to publish a new package, but no time to develop django-guardin in wider area.

**Comment by carltongibson** [comment]
Hi @ad-m. It looks like all the work has been done here: https://github.com/django-guardian/django-guardian/compare/master...devel

Any chance of a release, because we're looking at failures on DRF (from guardian 1.4.9) against Django 2.2 and `master`?

Thanks for your effort!

**Comment by ad-m** [comment]
@ad-m Please write as pull request a summary of these changes to which you have given the link. Not every commit is worth placing in the changelog.

**Comment by carltongibson** [comment]
Here you go #601

**Comment by ad-m** [comment]
New release available: https://github.com/django-guardian/django-guardian/releases/tag/v1.5.0

**Comment by carltongibson** [comment]
Well done @ad-m! Thanks!
