### ISSUE TITLE
remove_perm doesn't work with permission object

### ISSUE THREAD

**Issue by Dineshs91** [django-guardian/django-guardian#606]
`assign_perm` works with a permission object, but `remove_perm` doesn't work with the object.

Looking into the code I've found that, `assign_perm` [checks](https://github.com/django-guardian/django-guardian/blob/devel/guardian/shortcuts.py#L77) if it is an instance. But the same check is missing for `remove_perm`.

**Comment by EduOnieva** [comment]
Hello, does this have been fixed?
