### ISSUE TITLE
Documentation not up to date with migrations

### ISSUE THREAD

**Issue by beruic** [django-guardian/django-guardian#609]
I see a lot of mentioning of `syncdb` and south in the documentation. This does not make sense with todays migrations in Django.

**Comment by ad-m** [comment]
@beruic, could you provide pull requests for that? The project is based on the contribution of volunteers. We do not have constant, commercial project care.

**Comment by beruic** [comment]
I could, but I don't have time available for it, unless my company decides to use django-guardian for the project we are working on. I just thought it nice to notify this, since I noticed it during our investigations. The thing is, that django-guardian was almost discarded as a viable option because of this very old stuff in the documentation.

**Comment by ad-m** [comment]
Django-guardian is a project that has a stable scope of functionality, its source code is in good condition, the code is periodically up to the latest version of Django. Documentation, unfortunately, is not updated very often, but it is related to small in functionalities.

**Comment by ad-m** [comment]
Fixed. It looks we have bugs in docs update (#618). Fixed & no "syncdb" in guides now.
