### ISSUE TITLE
`assign_perm` should treat lists as querysets

### ISSUE THREAD

**Issue by duoi** [django-guardian/django-guardian#610]
Currently the `assign_perm` shortcut looks to see if `obj` is `None`, an instance of `Permission`, or an instance of `QuerySet` before treating it as an individual object.

The `QuerySet` check should contain an `or` to check if it's also a `list` since usage is the same.

**Comment by DavisRayM** [comment]
I'd like to pick this up, if its open....

**Comment by duoi** [comment]
> I'd like to pick this up, if no one is working on it.

It’s all yours. Go for it.
