### ISSUE TITLE
ReadTheDocs missing 1.5.0, 1.5.1 and 2.0.0 releases

### ISSUE THREAD

**Issue by johnthagen** [django-guardian/django-guardian#618]
The current latest published docs are several years out of date: https://django-guardian.readthedocs.io/

The last release is 1.4.9 from 2017. It was quite confusing as a new user to be reading the old docs and not realize how out of date they were until much later.

Could 1.5.0, 1.5.1, and 2.0.0 be added to that site?

**Comment by ad-m** [comment]
@lukaszb could you add "adobrawy" as maintainer on readthedocs.io?

**Comment by jagooding** [comment]
Can the documentation be auto built and uploaded as a part of the release process?

**Comment by ad-m** [comment]
The documentation should be automatically built for each commit on the "master" branch. That's how readthedocs works, and that's how it was before. Due to changes in permissions in GitHub, the process has been stopped and must be set up again.

**Comment by ad-m** [comment]
I sent an e-mail. In the absence of a response, we will abandon the current readthedocs.io and we will build the documentation in a different way than before.

**Comment by brianmay** [comment]
It looks like this has already been done, you should have access.

**Comment by ad-m** [comment]
@brianmay , I asked @lukaszb  directly & got answer with access immediatly. Builds fixed. Docs for 1.5.0, 1.5.1, 2.0.0 and ```latest``` fixed & builded. :fireworks:

**Comment by johnthagen** [comment]
@ad-m The `latest` read the docs link doesn't seem to be pointing to the latest. Is the `master` branch build not set up properly?

See this: https://django-guardian.readthedocs.io/en/latest/userguide/assign.html
Versus: https://django-guardian.readthedocs.io/en/stable/userguide/assign.html

Also, it seems like 2.0.0 link is broken?: https://django-guardian.readthedocs.io/en/v2.0.0/userguide/assign.html

**Comment by ad-m** [comment]
> The latest read the docs link doesn't seem to be pointing to the latest. Is the master branch build not set up properly?
I verified & setup one more time webhooks integration. I hope it will works now. 
> Also, it seems like 2.0.0 link is broken?
It works now . I triggered build for 2.0.0 manually again at https://readthedocs.org/projects/django-guardian/builds/.

**Comment by johnthagen** [comment]
@ad-m Looks good now, thanks!
