### ISSUE TITLE
Point of GroupObjectPermission and UserObjectPermission tables if using direct foreign keys

### ISSUE THREAD

**Issue by viseshrp** [django-guardian/django-guardian#629]
I'm currently looking at this project to build a per-item permission feature for an app. It mentions the option to use Direct foreign keys as a performance improvement suggestion. As the initial migrations that come with the app have similar models but with a Generic foreign key, I'm wondering if I can just remove the models/migrations from the package as they would just be two unnecessary tables, if I choose to go with the Direct FK approach. This must also be documented and I'd be happy to do a PR.

**Comment by ad-m** [comment]
So far, none of the users using DFK have complained about redundant tables. We are open to making the generic model optional if the implementation does not significantly increase the complexity of the code or the actions necessary to maintain it in the future.

The generic model has a reference in few places and I'm afraid that making it optional may not be trivial, but I probably don't see some smart idea. For this patch to be merged, it is critical that the profit from removing two tables does not increase the cost of maintaining the code in the future.

**Comment by viseshrp** [comment]
@ad-m So, my OCD could not get over two redundant and completely unused tables. I ended up making a fork of the library, making the two models abstract and then deleting the migrations. It seems to be working fine so far. Hopefully, this won't affect anything because the GFK models are still there, and if guardian is working as expected, it should just use my DFK models automatically and the removal of the GFK models should not affect anything. I will continue testing though. I don't have any real ideas for a PR to make this optional in the library itself, but I hope to at some point.
Thanks for your help.
