### ISSUE TITLE
post_migrate signal always uses the default database

### ISSUE THREAD

**Issue by AdamZ** [django-guardian/django-guardian#630]
In the `create_anonymous_user` function, the user lookup and save calls don't specify the `using` parameter/method call. This causes the operations to always apply to the default database, even if the migration is occurring on a different database.

It [looks like](https://docs.djangoproject.com/en/2.2/ref/signals/#post-migrate) the post_migrate signal sends a `using` parameter to the callback to tell it which DB is used, so it should be simple to add it to the `get()` and `save()` calls in the signal handler.

**Comment by ad-m** [comment]
Could you provide PR for that?

**Comment by ad-m** [comment]
Could you close that issue?
