### ISSUE TITLE
User should not be able to change a model it only has access to in Django Admin

### ISSUE THREAD

**Issue by elimayor** [django-guardian/django-guardian#643]
Hi,

I am facing the following issue. I want to be able to allow Users to view and/or change specific objects of my Team model in the Admin interface. So I allow user George to view and change Team 1. I then grant user George permission to VIEW team 2. Now, if I grant George global view access but not global change access, then George can view both teams, but can't edit either of them. If I also grant George global change access, he can now change BOTH teams, even though he should only be able to change Team 1. 

How can I resolve this?

**Comment by ad-m** [comment]
Could you provide any example code to reproduce it for example as fork of our example project?

**Comment by elimayor** [comment]
I have forked the example project.

I created a user George with password = 1234

I granted permission to view and change post 2, and only view post 1. 
I also granted global view permission to George.

If you log in with George, you'll see he cannot change post 2 nor post 1. 

If you try to give George global change permissions, he can then change post 1 even though you wouldn't want that (didn't give him the specific change post 1 permission)

**Comment by ad-m** [comment]
Do I understand correctly that you expect a situation where a user has global permission to deny him access due to a lack of permission? For django-guardian, granting permission globally means that it has the right to all objects by default. In some function there is parameter ```accept_global_perms``` to manage that.
