### ISSUE TITLE
OR-check instead AND-check in PermissionRequiredMixin?

### ISSUE THREAD

**Issue by lambdafu** [django-guardian/django-guardian#665]
Hi,

I noticed (with @TheRadialActive) that if I use PermissionRequiredMixin with a list for permissions_required, the access will be granted only if all permissions are held by the user, due to the use of the all-reducer in get_40x_or_None, which uses all(). However, there are cases where it is interesting to verify if any of some permissions are held, which currently does not seem to be possible. Do you have any advice on this?  Duplicating the code and changing all to any is simple enough, but maybe there are other solutions already available, or you might want to add a way to configure this behaviour. Thanks!

**Comment by RainshawGao** [comment]
@lambdafu @ad-m #697 has add `any_perm` to `get_40x_or_None`, so this issue can be closed.
