### ISSUE TITLE
Is guardian creating a N*M table for N users and M objects?

### ISSUE THREAD

**Issue by BoPeng** [django-guardian/django-guardian#678]
I am creating a project that currently uses a bunch of `obj.can_xxx(user)` functions to test if `xxx` can be performed by user for certain object, using logics such as if `user` is authenticated and `user` belong to group `A` with permission `X` and `obj` is viewable by any user or group with permission `X`. The problem for this approach is that, for example, if I want to get a list of objects that user can `xxx`, I will have to get all objects and filter by `can_xxx` (or re-implement the same logic at the global level).

I came across `django-guardian` which seems to be a perfect solution for my problem, but I cannot seem to get a big picture of how guardian works. As far as I can tell, guardian creates a table (many to many relationship) with permission for each user and object, so the size of the table could be `N*M` if there are `N` users and `M` objects even if we do not consider complications such as groups and multiple permissions. Will this be a problem for large number of users and/or objects? Also, how would permission be updated with the change of objects? For example, if the status of an object is changed from `PUBLISHED` to `ARCHIVED`, do I have to change permission for all users? Basically I am thinking where I should define my complex logics of if `user` can do something to `obj` according to both `user` and `obj` properties.

**Comment by ad-m** [comment]
>  As far as I can tell, guardian creates a table (many to many relationship) with permission for each user and object, so the size of the table could be N*M if there are N users and M objects even if we do not consider complications such as groups and multiple permissions. 

Even worse, because middle table contains N*M*O object where:
- N - users
- M - objects
- O - permissions granted per user per object

When you have user ```A``` with permission ```publish``` and ```delete``` on object ```C`` there is following rows in middle table:
``
A | C | publish
A | C | delete
```

> Will this be a problem for large number of users and/or objects?

Usually it's not a problem due indexing of data in relation database and hardly use of JOIN in our library.

> Also, how would permission be updated with the change of objects?

Permission in our library is not related to data of objects. In this case, you must implement the addition / removal of permission for object in your own application alone, or use another library that can grant permissions based on attributes (attribute based access control).

> For example, if the status of an object is changed from PUBLISHED to ARCHIVED, do I have to change permission for all users?

Yes.

**Comment by BoPeng** [comment]
Many thanks for your clarification.

**Comment by BoPeng** [comment]
@ad-m Could you clarify if `guardian` would be applied to all models, or selected models with `permissions`? Right now I am thinking of some `type objects` that conceptualize the type of my real `objects` (e.g. `PUBLISHED` and `ARCHIVED` etc) and assign permissions to these type objects. In this way change the status of `objects` will not affect `type objects`, and the permission check would be something like `has_permission('xxx', obj.type())` instead of `has_permission('xxx', obj)`. The permission table will therefore be substantially smaller.

The remaining question is that if `guardian` will create permission tables for all models, or models only with`permission` in  `Meta` class. Since `django` has default permissions, I am afraid that a huge permission table would be created for my `object` model as well.

**Comment by ad-m** [comment]
> Could you clarify if guardian would be applied to all models,

All.

> create permission tables for all models, or models only withpermission in Meta class

Django by default create permission for each model. Django-guardian create (by default) single permission table for all models using ```GenericForeignKey```. For performance purpose you can creat single model for specific model and use direct Foreign Key. It's already documented at https://django-guardian.readthedocs.io/en/stable/userguide/performance.html . 

> django has default permissions

Django-guardian does not assign any default permissions. This means that an additional model for which you have not assigned any user any privileges costs nothing.

**Comment by BoPeng** [comment]
> Permission in our library is not related to data of objects. In this case, you must implement the addition / removal of permission for object in your own application alone, or use another library that can grant permissions based on attributes (attribute based access control).

Just for anyone who might need object-level permission based on object attributes and came across this ticket, I have found [django-rules](https://github.com/dfunckt/django-rules) a perfect library for it.
