### ISSUE TITLE
get_objects_for_user broke on 2.2.0 from 2.1.0 for non int and non character varying primary keys

### ISSUE THREAD

**Issue by jmacul2** [django-guardian/django-guardian#688]
I user macaddr as a primary key for a big django project.  Non int primary keys worked fine with this shortcut function until release 2.2.0.  Now it is throwing:

`
Exception Type: ProgrammingError at /api/hosts/
Exception Value: operator does not exist: macaddr = character varying
LINE 1: ..."."search_index" FROM "hosts" WHERE "hosts"."mac" IN (SELECT...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
`

I might try working up a pull request in a few days.

**Comment by ad-m** [comment]
See #675

**Comment by aniforprez** [comment]
Has this not been resolved yet?

**Comment by ad-m** [comment]
@aniforprez see #675 . This is an open-source project fully managed by the community without any commercial support, so - if the issue is important to you - then you can take over pull requests and complete the changes (rebase, improve MySQL support).

**Comment by michael-k** [comment]
FYI: PR #675 has been superseded by PR #691
