### ISSUE TITLE
get_objects_for_user() breaks on PostgreSQL with inherited models

### ISSUE THREAD

**Issue by Maxr1998** [django-guardian/django-guardian#699]
## Bug description

Consider the following model structure:

```py
class Parent(django.db.models.Model):
    """
    Parent class, primary key is an AutoField
    """
    name = models.CharField(max_length=100)


class Child(Parent):
    """
    Subclass, inherits primary key from Parent, keeps a reference to the parent in an OneToOneField
    """
    data = models.CharField(max_length=100)
```

Now, calling `guardian.shortcuts.get_objects_for_user(user, 'permission', Child)` will crash the application due to a database exception, namely:
```
django.db.utils.ProgrammingError: operator does not exist: integer = character varying
<SQL>
```

The reason for this is a missing cast on the `object_pk` field from guardian (compare #366 for reference).
Through some debugging I found out that the issue lies in `guardian.shortcuts._is_cast_integer_pk`, which completely ignores the possibility of primary keys referenced through OneToOneFields (or other foreign key types).

## Proposal
ForeignKey fields like OneToOneFields should be explicitly handled in `_is_cast_integer_pk`. One solution I've come up with would be this:

```py
def _is_cast_integer_pk(queryset):
    return _is_cast_integer_pk_field(queryset.model._meta.pk)


def _is_cast_integer_pk_field(field):
    if isinstance(field, RelatedField):
        return _is_cast_integer_pk_field(field.related_model._meta.pk)

    return isinstance(field, (
        IntegerField, AutoField, BigIntegerField,
        PositiveIntegerField, PositiveSmallIntegerField,
        SmallIntegerField))
```

Alternatively, one could use the `cast_db_type` something like this:
```py
def _is_cast_integer_pk(queryset):
   return queryset.model._meta.pk.cast_db_type(transaction.get_connection(queryset.db)) == 'integer'
```

If you want, I can make a PR ready tomorrow.

**Comment by michael-k** [comment]
This has been fixed in devel: https://github.com/django-guardian/django-guardian/blame/devel/guardian/shortcuts.py#L802-L831.  Can you confirm that the fix works for your use case?

**Comment by Maxr1998** [comment]
Thank you, I can confirm that pulling in the latest shortcuts.py from master fixes the issue. Closing this issue then.
