### ISSUE TITLE
audiofield throws arror

### ISSUE THREAD

**Issue by Smartybrainy** [django-guardian/django-guardian#703]
I am new in django and want to add audio file to my new blog app and the documentation instructs me to install and add audiofield to the list of my INSTALLED_APP in settings.py, but after adding the 'audiofield', all I see is error. showing the below.

ERRORS:
audiofield.AudioFile: (auth.E005) The permission codenamed 'view_audiofile' clashes with a builtin permission for model 'audiofield.AudioFile'.

I have search all over the internet and there is no solution that could fix this issue.
Please I will appreciate if anyone have and idea of what codename if and how to fix this problem

Please

**Comment by ad-m** [comment]
This is not an "audiofield" repository.

**Comment by michael-k** [comment]
@Smartybrainy see areski/django-audiofield#34
