### ISSUE TITLE
Tests CI fail - Can't connect to local MySQL server through socket

### ISSUE THREAD

**Issue by ad-m** [django-guardian/django-guardian#718]
```
_mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
```

We need fix CI workflow. All build on CI fail now. It blocks any merge to project.

**Comment by michael-k** [comment]
Seems to work againt, but Travis is incredibly slow.  I've started working on switching to GitHub Actions a while ago but didn't finish it.  I'll look into it and hopefully open a PR in the next couple of days.

**Comment by ad-m** [comment]
I like idea to migrate to GitHub Actions.
