### ISSUE TITLE
@permission_required does not work on methods

### ISSUE THREAD

**Issue by dchiquito** [django-guardian/django-guardian#723]
The `@permission_required` decorator only works on view functions, not methods.
Specifically, [django-rest-framework](https://www.django-rest-framework.org/) lets you define ViewSets, which are classes that make it easy to quickly define a family of views for a model. Instead of defining individual view functions, you create a class which extends ViewSet, and create view methods on that class.

I would like to be able to do something like this:
```
class MyViewSet(ReadOnlyModelViewSet):
    ...
    @action(methods=['POST'])
    @permission_required('top_secret_clearance')
    def customize(self, request, pk):
        ... do the thing ...
```

However, the `permission_required` decorator is defined like this:
```
def permission_required(perm, lookup_variables=None, **kwargs):
    def decorator(view_func):
        def _wrapped_view(request, *args, **kwargs):
            ... permission checking ...
```
`_wrapped_view` only takes one argument, `request`, but when you use `@permission_required` on a method (not a function), it is passed `self, request` instead. `_wrapped_view` then assumes that `self` is actually `request`, and `request` is just one of the `*args`, and then fails when the ViewSet is not a request object.

**Comment by RainshawGao** [comment]
have you try to use `django.utils.decorators.method_decorator` ?
like in https://docs.djangoproject.com/zh-hans/3.1/topics/class-based-views/intro/#id1, use method_decorator with permission_required may work

**Comment by dchiquito** [comment]
I believe that is exactly what I'm looking for, thanks!
