### ISSUE TITLE
How to assign global permission to an object of group

### ISSUE THREAD

**Issue by krodh** [django-guardian/django-guardian#734]
I am figuring out a way to assign global permission to object. When I try:
```python3
assign_perm('app_name.codename', group, object)
```
It raises NotFound, I tried it with passing permission object but still it returns same error.

**Comment by ad-m** [comment]
All permission is global. Permission can be assigned globally / per object to user / group.

Are you able assign expected permission configuration via django-admin? Have you generated & applied all pending migrations?

**Comment by krodh** [comment]
Via django-admin I can assign only add, change, delete, and view permissions of that model to that object. I can't add other model permission to that object.
I think this will not work as I want but is there other similar way of doing it?

**Comment by ad-m** [comment]
You can not assign permission of models X to objects with model Y. Model of permission and type of object must match . I suggest update permission of model Y.

**Comment by krodh** [comment]
I implemented your suggestion into my code, and it worked. Thanks for your suggestion.
