### ISSUE TITLE
Update classifiers for Python 3.9

### ISSUE THREAD

**Issue by hirusi** [django-guardian/django-guardian#745]
Hello! New to the Python ecosystem! I noticed that the Tox setup include Python 3.9 and Django 3.2 RC1. On PyPi, I only saw support up until Python 3.8 -- I believe it would be easy to add a classifier for Python 3.9 assuming the test suite passes.

**Comment by johnthagen** [comment]
The trove classifier is already updated, there just hasn't been a release pushed to PyPI in some time: https://github.com/django-guardian/django-guardian/blob/f3b3e716483b58626363bf802a6ef9a24247371b/setup.py#L51

**Comment by hirusi** [comment]
Oh no, my had.

**Comment by johnthagen** [comment]
@ad-m Any chance of a new `django-guardian` release with Django 3.2 support? I know the DRF folks have been hopefully for a new release: https://github.com/encode/django-rest-framework/pull/7927#issuecomment-821307614
