### ISSUE TITLE
Test against and update classifiers for final Django 3.2 release

### ISSUE THREAD

**Issue by hirusi** [django-guardian/django-guardian#746]
I noticed that the tox configuration already includes Django 3.2 RC1. It would be lovely if it is updated to test against 3.2 final, as well as if the tests pass, that the classifiers are updated to include Django 3.2 (final).

**Comment by hirusi** [comment]
One related PR on this front is https://github.com/django-guardian/django-guardian/pull/740

**Comment by johnthagen** [comment]
The 3.2 classifier was already added in ffdbec8a9843fa0cc16b31cbb6fe89a409221877.
