### ISSUE TITLE
Upload a new release to PyPI

### ISSUE THREAD

**Issue by johnthagen** [django-guardian/django-guardian#747]
Users have been asking about Python 3.9 support (#745) and the DRF folks have been hoping to update their test suit for Django 3.2 (https://github.com/encode/django-rest-framework/pull/7927#issuecomment-821307614) but not having a recent release on PyPI blocks these.

@ad-m Could a new release be published to PyPI?

**Comment by ad-m** [comment]
New version released: https://pypi.org/project/django-guardian/2.4.0/
