### ISSUE TITLE
django-guardian django-admin

### ISSUE THREAD

**Issue by kerwinxu** [django-guardian/django-guardian#761]
1.  create class QuestionAdmin(GuardedModelAdmin):
2. admin.site.register(Question, QuestionAdmin)
3. run python manage.py makemigrations
4. run python manage.py migrate
5. create user kerwin and set all permissions to object of Question .
6. I login kerwin  in http://127.0.0.1:8000/admin , but show nothing .
7. I login admin(superuser)  and set  view permission to Kerwin .
8. I login kerwin , show anything , include question of admin(other users) .

**Comment by kerwinxu** [comment]
I know how to do it .

**Comment by ociule** [comment]
Hi Kerwin,

I just tested this example with Django 3.2 and the latest release of Django-Guardian and it worked with this fix: change 'polls.change_choice' to 'polls.view_choice' (as you've said you gave Kerwin view permission, not change).

I didn't find a complete example anywhere else but the following works as expected, only showing the rows for which the user has view permission (and also checks for change)

```python
class ChoiceAdmin(GuardedModelAdmin):

    def get_permission_codename(self, action):
        opts = self.opts
        return f"{opts.app_label}.{get_permission_codename(action, opts)}"

    def get_queryset(self, request):
        query = super().get_queryset(request)
        if request.user.is_superuser:
            return query

        return get_objects_for_user(request.user, self.get_permission_codename('view'))

    def has_module_permission(self, request):
        if request.user.is_superuser:
            return True

        qs = get_objects_for_user(request.user, self.get_permission_codename('view'))
        return qs.count() > 0

    def has_view_permission(self, request, obj=None):
        if request.user.is_superuser:
            return True
        if obj != None:
            return request.user.has_perm(self.get_permission_codename('view'), obj)
        else:
            return True

    def has_change_permission(self, request, obj=None):
        if request.user.is_superuser:
            return True
        if obj != None:
            return request.user.has_perm(self.get_permission_codename('change'), obj)
        else:
            return True
```

**Comment by ad-m** [comment]
> ```python
>     def get_queryset(self, request):
>         query = super().get_queryset(request)
>         if request.user.is_superuser:
>             return query
> 
>         return get_objects_for_user(request.user, self.get_permission_codename('view'))
> ```

`guardian.shortcuts.get_objects_for_user` have parameter `with_superuser` which by default use `True`, so it is redundant to check.

**Comment by ociule** [comment]
Thanks ad-m! 

This simplifies the proposed code to:

```py
class ChoiceAdmin(GuardedModelAdmin):

    def get_permission_codename(self, action):
        opts = self.opts
        return f"{opts.app_label}.{get_permission_codename(action, opts)}"

    def get_queryset(self, request):
        return get_objects_for_user(request.user, self.get_permission_codename('view'))

    def has_module_permission(self, request):
        qs = get_objects_for_user(request.user, self.get_permission_codename('view'))
        return qs.count() > 0

    def has_view_permission(self, request, obj=None):
        if obj != None:
            return request.user.has_perm(self.get_permission_codename('view'), obj)
        else:
            return True

    def has_change_permission(self, request, obj=None):
        if obj != None:
            return request.user.has_perm(self.get_permission_codename('change'), obj)
        else:
            return True
```

**Comment by ociule** [comment]
I have tested the proposed solution. Given it works, IMO it's OK to close this issue.
