### ISSUE TITLE
Enabling Discussions on the repo

### ISSUE THREAD

**Issue by iamMHZ** [django-guardian/django-guardian#798]
@ad-m 
It would be really nice to have the Discussions on the repo. It helps in many ways.

**Comment by iamMHZ** [comment]
@django-guardian

**Comment by johnthagen** [comment]
@thclark @cmaggiulli Perhaps you have permissions to do this now?

**Comment by cmaggiulli** [comment]
> @thclark @cmaggiulli Perhaps you have permissions to do this now?

Unfortunately I do not believe I have the access to enable discussions.  @thclark  if you want to enable discussions I wrote a sample introductory post https://github.com/cmaggiulli/django-guardian/discussions/1 feel free to use that and/or rearrange as desired

**Comment by thclark** [comment]
I definitely support this, but no, sadly I don't have permission to do much. I'd also like to enable projects at the same time so I could put together a roadmap. And tidy up all the weird branches.

@brianmay are you able to enable discussions?

**Comment by brianmay** [comment]
Done.
