### ISSUE TITLE
Provide a shortcut function for "reassigning" user permissions.  

### ISSUE THREAD

**Issue by cmaggiulli** [django-guardian/django-guardian#810]
Please take a look at my [StackOverflow Question](https://stackoverflow.com/questions/77431461/reassign-all-guardian-user-object-permissions-from-one-django-user-to-another-dj) for the exact use case.  Most large systems I've worked on have access/identity management automation for linking multiple accounts to a single identity.  Very often there are reasons an "account" may need to be merged with another account.  I was very surprised that I was not able to easily accomplish this using the various shortcut functions provided by the SDK.  I would like to see some type of user permission reassignment capabilities

**Comment by cmaggiulli** [comment]
Is anyone opposed to me adding this as a shortcut method?

**Comment by thclark** [comment]
I have no objections!!! :)

**Comment by cmaggiulli** [comment]
Ok I’ll create a PR today

**Comment by cmaggiulli** [comment]
Actually - Im going to hold off on this temporarily pending https://github.com/django-guardian/django-guardian/discussions/821 discussion.  Additionally, I almost feel like this should be something that lives in the model manager so that if we do something like

`permissions = UserObjectPermission.objects.filter(content_type=1, is_polymorphic_permission_class_aware=True)`

whereby when this filter method on manager is called with is_polymorphic_permission_class_aware=True (which is obv false by default) then it will look to see if there is a specific <ContentType>UserObjectPermission class that inherits UserObjectPermissionBase and it will operate on that model.  I feel like this is a better solution BUT we should discuss https://github.com/django-guardian/django-guardian/discussions/821

**Comment by cmaggiulli** [comment]
As such - because of Disc 821 and the fact that, if we decide this is warranted, it shouldn't be added as a shortcut IMO but as a feature on the Manager, I am closing this
