### ISSUE TITLE
get_perms and get_user_perms are returning different results

### ISSUE THREAD

**Issue by giancastro** [django-guardian/django-guardian#824]
Idk when it started to happen, but now the `get_perms` and `get_user_perms` are returning different results for the same user and object.

For instance:

```
In [49]: shortcuts.get_perms(user, easement)
Out[49]: ['add_easement', 'change_easement', 'delete_easement', 'view_easement']

In [50]: shortcuts.get_user_perms(user, easement)
Out[50]: <QuerySet ['view_easement']>
```

The `get_obj_perms` tag is also having the same bug.

**Comment by jmsmkn** [comment]
Isn't the explanation in the doc string:

https://github.com/django-guardian/django-guardian/blob/8c136ba7bb161657a4bea89b0d8bb88e690958b6/guardian/shortcuts.py#L200-L204

https://github.com/django-guardian/django-guardian/blob/8c136ba7bb161657a4bea89b0d8bb88e690958b6/guardian/shortcuts.py#L209-L213

So `'view_easement'` is assigned directly and `['add_easement', 'change_easement', 'delete_easement']` (and potentially `'view_easement'` again) are assigned via groups the user is a member of?

**Comment by giancastro** [comment]
The user has no groups.

**Comment by giancastro** [comment]
```
In [6]: shortcuts.get_perms(user, easement)
Out[6]: ['add_easement', 'change_easement', 'delete_easement', 'view_easement']

In [7]: shortcuts.get_user_perms(user, easement)
Out[7]: <QuerySet ['change_easement', 'view_easement']>

In [8]: shortcuts.remove_perm("change_easement", user, easement)
Out[8]: (1, {'guardian.UserObjectPermission': 1})

In [9]: shortcuts.get_perms(user, easement)
Out[9]: ['add_easement', 'change_easement', 'delete_easement', 'view_easement']

In [10]: shortcuts.get_user_perms(user, easement)
Out[10]: <QuerySet ['view_easement']>

In [11]: user.groups.all()
Out[11]: <QuerySet []>
```

**Comment by giancastro** [comment]
There's no bug, the reason for that is that the user is an admin.
