### ISSUE TITLE
Permission fails for user

### ISSUE THREAD

**Issue by RicardoRobledo** [django-guardian/django-guardian#826]
I get True when I verify a permission that does not exists

![image](https://github.com/user-attachments/assets/275ad661-78a6-4c43-948e-5780c13b2d8d)

**Comment by thclark** [comment]
Hi @RicardoRobledo when using `u.has_perm` in the way you are, this isn't checking for object-level permissions. This is a check for django's built in role-based permission. I'd recommend working through the [user guide](https://django-guardian.readthedocs.io/en/stable/userguide/index.html).
